/*
lrc: dropbox.com
storage: archive.org
storage: dropbox.com
author: by XuanKen
creat year: 2021-2022-2023-2024
website 1: karaokenb.ga
website 2: nhacbuon.tk
website 3: clipnb.ga
*/
const ap = new APlayer({
    container: document.getElementById('player'),
    mini: false,
    lrcType: 3,
    loop: 'all',
    order: 'random',
    preload: 'metadata',
    listFolded: true,
    listMaxHeight: 660,
    showlrc: true,
    volume: 100,
    autoplay: true,
    audio: [
        {
            name: 'Người Cũ Còn Yêu',
            artist: 'Pha Phạm',
            url: 'https://archive.org/download/musicnewxk/NguoiCuConYeu-PhaPham.mp3',
            cover: 'https://i.imgur.com/O9jMw1W.jpeg',
            theme: '#5d557a',
        },
        {
            name: 'Nơi Vực Nơi Trời (Ballad)',
            artist: 'Lê Bảo Bình',
            url: 'https://archive.org/download/musicnewxk/NoiVucNoiTroiBallad-LeBaoBinh.mp3',
            cover: 'https://i.imgur.com/pQ1r8G2.jpg',
            theme: '#94b1e1',
        },
        {
            name: 'Cánh Hoa Héo Tàn',
            artist: 'Mochiii',
            url: 'https://archive.org/download/musicnewxk/CanhHoaHeoTan-MoChiii.mp3',
            cover: 'https://i.imgur.com/SnLmYh5.jpeg',
            theme: '#47e5e7',
        },
        {
            name: 'Anh Đau Từ Lúc Em Đi',
            artist: 'Trần Mạnh Cường',
            url: 'https://archive.org/download/musicnewxk/AnhDauTuLucEmDi-TranManhCuong.mp3',
            cover: 'https://i.imgur.com/haiOk7J.jpeg',
            theme: '#2dd906',
        },
        {
            name: 'Nhường Người Đến Sau',
            artist: 'Mochiii',
            url: 'https://archive.org/download/musicnewxk/NhuongNguoiDenSau-Mochiii.mp3',
            cover: 'https://i.imgur.com/SnLmYh5.jpeg',
            lrc: 'lyric/NhuongNguoiDenSau-Mochiii.lrc',
            theme: '#2f3291',
        },
        {
            name: 'Cảm Ơn Em',
            artist: 'Đặng Thiên Chí',
            url: 'https://archive.org/download/musicnewxk/CamOnEm-ThienChi.mp3',
            cover: 'https://i.imgur.com/l3UvVz7.jpeg',
            lrc: 'https://nokiapro.github.io/xuanken/lyric/CamOnEm-DangThienTri.lrc',
            theme: '#66c6da',
        },
        {
            name: 'Người Về Phương Xa (Cover)',
            artist: 'Kiều Thơ',
            url: 'https://archive.org/download/musicnewxk/NguoiVePhuongXaCover-KieuTho.mp3',
            cover: 'https://i.imgur.com/RVh4Mk6.jpeg',
            theme: '#d91ae9',
        },
        {
            name: 'Kết Thúc Bất Ngờ',
            artist: 'Nguyễn Vĩ',
            url: 'https://archive.org/download/musicnewxk/KetThucBatNgo-NguyenVi.mp3',
            cover: 'https://i.imgur.com/LGlG961.jpeg',
            theme: '#4c789b',
        },
        {
            name: 'Bán Nguyệt Ly Tâm',
            artist: 'Thiên Tú',
            url: 'https://archive.org/download/musicnewxk/BanNguyetLyTam-ThienTu.mp3',
            cover: 'https://i.imgur.com/ocfO6br.jpeg',
            theme: '#7434f4',
        },
        {
            name: 'Hẹn Anh Khi Hoa Chưa Tàn (Cover)',
            artist: 'Bảo Vân',
            url: 'https://archive.org/download/musicnewxk/HenAnhKhiHoaChuaTanCover-BaoVan.mp3',
            cover: 'https://i.imgur.com/R33q24c.jpeg',
            theme: '#35add1',
        },
        {
            name: 'Ai Chung Tình Được Mãi (Rumba)',
            artist: 'Mochiii',
            url: 'https://archive.org/download/musicnewxk/AiChungTinhDuocMaiRumba-MoChiii.mp3',
            cover: 'https://i.imgur.com/SnLmYh5.jpeg',
            lrc: 'lyric/AiChungTinhDuocMaiRumba-MoChiii.lrc',
            theme: '#32a504',
        },
        {
            name: 'Anh Thôi Nhân Nhượng',
            artist: 'An Clock',
            url: 'https://archive.org/download/xkms_20240317/anhthoinhannhuong.mp3',
            cover: 'https://i.imgur.com/HuG0b8n.jpeg',
            theme: '#e04ebf',
        },
        {
            name: 'Mộng Hoa Sim',
            artist: 'Thiên Tú',
            url: 'https://archive.org/download/musicnewxk/MongHoaSim-ThienTu.mp3',
            cover: 'https://i.imgur.com/ocfO6br.jpeg',
            theme: '#2a8367',
        },
        {
            name: 'Vũ Trụ Trong Anh',
            artist: 'Hoàng Lan',
            url: 'https://dl.dropboxusercontent.com/s/sdl518f7rushuh6/Vu-Tru-Trong-Anh-Hoang-Lan.mp3',
            cover: 'https://i.imgur.com/KJM4UGA.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/vvye830ic2vdt36/Vu-Tru-Trong-Anh.lrc',
            theme: '#894c67',
        },
        {
            name: 'Chạy Về Nơi Phía Anh',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/fovm1smh3epja7t/Chay-Ve-Noi-Phia-Anh-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/a8abq7yn0lvdoyv/Chay-Ve-Noi-Phia-Anh.lrc',
            theme: '#7c96a2',
        },
        {
            name: 'Phố Một Người',
            artist: 'Hồ Quang Hiếu, TĐQ',
            url: 'https://dl.dropboxusercontent.com/s/81hsf6zryvn72yf/Pho-Mot-Nguoi-Ho-Quang-Hieu-Trinh-Dinh-Quang.mp3',
            cover: 'https://i.imgur.com/ioVNUuJ.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ohqb1pevgywpero/Pho-Mot-Nguoi.lrc',
            theme: '#fc9f09',
        },
        {
            name: 'Lời Nói Dối Sau Nụ Cười',
            artist: 'K-ICM',
            url: 'https://dl.dropboxusercontent.com/s/4i32vwtih74mq8k/Loi-Noi-Doi-Sau-Nu-Cuoi-K-ICM.mp3',
            cover: 'https://i.imgur.com/PeW1GxI.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/k5kqgysb7ia7su5/Loi-Noi-Doi-Sau-Nu-Cuoi.lrc',
            theme: '#d2e992',
        },
        {
            name: 'Xa Vắng',
            artist: 'Jack Viet Nam',
            url: 'https://dl.dropboxusercontent.com/s/p5suvksj1ubvmco/Xa-Vang-Jack-Viet-Nam.mp3',
            cover: 'https://i.imgur.com/HOJa0jv.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/pn1pr6d3cdj8b3a/Xa-Vang-Jack-Viet-Nam.lrc',
            theme: '#28dd01',
        },
        {
            name: 'Còn Duyên Thì Bên Nhau',
            artist: 'Thái Học',
            url: 'https://dl.dropboxusercontent.com/s/ynjhxq7tpmw8p8s/Con-Duyen-Thi-Ben-Nhau-Thai-Hoc.mp3',
            cover: 'https://i.imgur.com/ZFL7rqa.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/8bnsdt825yb8pvw/Con-Duyen-Thi-Ben-Nhau.lrc',
            theme: '#9861bc',
        },
        {
            name: 'Quên Đi Thì Hơn',
            artist: 'Thanh Hưng',
            url: 'https://dl.dropboxusercontent.com/s/avupcy2sbniel8l/Quen-Di-Thi-Hon-Thanh-Hung.mp3',
            cover: 'https://i.imgur.com/Jq5iCzV.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/8omjxct24abhhvh/Quen-Di-Thi-Hon.lrc',
            theme: '#824706',
        },
        {
            name: 'Thôi, Quên Đi',
            artist: 'Phát Huy T4, TVk',
            url: 'https://dl.dropboxusercontent.com/s/9o0b2v1dgrpzw2b/Thoi-Quen-Di-Phat-Huy-T4.mp3',
            cover: 'https://i.imgur.com/qJ6zA8N.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/gklusah9ksdmffm/Thoi-Quen-Di.lrc',
            theme: '#76c7e5',
        },
        {
            name: 'Rồi Nâng Cái Ly',
            artist: 'Nal',
            url: 'https://dl.dropboxusercontent.com/s/qn9tm0vpghx7ckx/Roi-Nang-Cai-Ly-Nal.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/q3t2hit4rwl5f04/Roi-Nang-Cai-Ly.lrc',
            theme: '#a458b5',
        },
        {
            name: 'Phút Chia Lìa',
            artist: 'NB3 Hoài Bảo, H-Kray',
            url: 'https://dl.dropboxusercontent.com/s/e8delx8z982walv/Phut-Chia-Lia-NB3-Hoai-Bao.mp3',
            cover: 'https://i.imgur.com/nK5R2GZ.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/jhmvbrj5s2ext36/Phut-Chia-Lia.lrc',
            theme: '#fefadc',
        },
        {
            name: 'Tình Cờ Gặp Cố Tình Yêu',
            artist: 'Shine Thành Anh',
            url: 'https://dl.dropboxusercontent.com/s/xgs88tmvd3ctbne/Tinh-Co-Gap-Co-Tinh-Yeu-Shine-Thanh-Anh.mp3',
            cover: 'https://i.imgur.com/lblWjxp.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/18blzrl2lwt10ve/Tinh-Co-Gap-Co-Tinh-Yeu.lrc',
            theme: '#10c1f9',
        },
        {
            name: 'Bên Em Anh Mới Hiểu',
            artist: 'Huy Vạc, An Vũ',
            url: 'https://dl.dropboxusercontent.com/s/5cmsqt3agq3vzht/Ben-Em-Anh-Moi-Hieu-Huy-Vac.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/uvwims3khucxop5/Ben-Em-Anh-Moi-Hieu.lrc',
            theme: '#11546f',
        },
        {
            name: 'Anh Sợ Mình Tan Vỡ',
            artist: 'Hồ Phong An',
            url: 'https://dl.dropboxusercontent.com/s/5vx74hvza4cabgs/Anh-So-Minh-Tan-Vo-Ho-Phong-An.mp3',
            cover: 'https://i.imgur.com/vk3rDtU.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/rk2ubevc6t6uqr2/Anh-So-Minh-Tan-Vo.lrc',
            theme: '#e79319',
        },
        {
            name: 'Chỉ Muốn Nói Cùng Em',
            artist: 'Kun',
            url: 'https://dl.dropboxusercontent.com/s/cxtc6v3idipee3x/Chi-Muon-Noi-Cung-Em-Kun.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            lrc: 'https://dl.dropboxusercontent.com/s/wilwgyqirlrtovu/Chi-Muon-Noi-Cung-Em.lrc',
            theme: '#d25411',
        },
        {
            name: 'Đành Lòng',
            artist: 'Bình Boo',
            url: 'https://dl.dropboxusercontent.com/s/q5lfjrwhnxkez32/Danh-Long-Binh-Boo.mp3',
            cover: 'https://i.imgur.com/WWPpIP2.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/whjwderwgzup0db/Danh-Long.lrc',
            theme: '#3434e2',
        },
        {
            name: 'Em Vội Quên',
            artist: 'Gia Huy Singer',
            url: 'https://dl.dropboxusercontent.com/s/r2kqs57ud54zu79/Em-Voi-Quen-Gia-Huy-Singer.mp3',
            cover: 'https://i.imgur.com/AU8XnLE.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/cwjpl7l3evmpesw/Em-Voi-Quen.lrc',
            theme: '#c8b1ab',
        },
        {
            name: 'Ôm Nhiều Mộng Mơ',
            artist: 'Phát Huy T4',
            url: 'https://dl.dropboxusercontent.com/s/kvf2zvd2818mywa/Om-Nhieu-Mong-Mo-Phat-Huy-T4.mp3',
            cover: 'https://i.imgur.com/qJ6zA8N.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/pyzn6ne80bpgjd7/Om-Nhieu-Mong-Mo.lrc',
            theme: '#bb546e',
        },
        {
            name: 'Hoa Tàn Tình Tan',
            artist: 'Giang Jolee',
            url: 'https://dl.dropboxusercontent.com/s/l2s6cywfhe4shp8/Hoa-Tan-Tinh-Tan-Giang-Jolee.mp3',
            cover: 'https://i.imgur.com/K10xJMz.jpg',
            theme: '#2f4f18',
        },
        {
            name: 'Thì Thôi',
            artist: 'Nal, TVk',
            url: 'https://dl.dropboxusercontent.com/s/1si5zl0irgko6cc/Thi-Thoi-Nal.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/4hqgrji3dtwenj5/Thi-Thoi.lrc',
            theme: '#e234ea',
        },
        {
            name: 'Em Gái Quê',
            artist: 'Sumo',
            url: 'https://dl.dropboxusercontent.com/s/ozgkq5aae62bkm2/Em-Gai-Que-Sumo-K-ICM.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            lrc: 'https://dl.dropboxusercontent.com/s/icdh3vwbzwipejk/Em-Gai-Que.lrc',
            theme: '#8083eb',
        },
        {
            name: 'Thanh Xuân Của Anh Là Em',
            artist: 'Nguyễn Đình Vũ',
            url: 'https://dl.dropboxusercontent.com/s/33xxw2tu1vqr3ga/Thanh-Xuan-Cua-Anh-La-Em-Nguyen-Dinh-Vu.mp3',
            cover: 'https://i.imgur.com/nbhcYYh.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ytlk79bzyirvrdy/Thanh-Xuan-Cua-Anh-La-Em.lrc',
            theme: '#fb42a7',
        },
        {
            name: 'Áo Cũ Tình Em',
            artist: 'Thương Võ',
            url: 'https://dl.dropboxusercontent.com/s/ik40sc8g39i4bnj/Ao-Cu-Tinh-Em-Thuong-Vo.mp3',
            cover: 'https://i.imgur.com/HYDm8yl.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/eml23pyxan99p9n/Ao-Cu-Tinh-Em.lrc',
            theme: '#386f6a',
        },
        {
            name: 'Phận Hoa Rơi',
            artist: 'Vicky Nhung',
            url: 'https://dl.dropboxusercontent.com/s/17mvsfpswlukbuf/Phan-Hoa-Roi-Vicky-Nhung-K-ICM.mp3',
            cover: 'https://i.imgur.com/mFoydiv.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/kf22o5ivacciqja/Phan-Hoa-Roi.lrc',
            theme: '#079e15',
        },
        {
            name: 'Cố Chấp Dù Anh Đau',
            artist: 'Châu Khải Phong',
            url: 'https://dl.dropboxusercontent.com/s/6u6i49lp1gxq357/Co-Chap-Du-Anh-Dau-Chau-Khai-Phong.mp3',
            cover: 'https://i.imgur.com/rCPAeVf.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/jz7o33nif99bm9y/Co-Chap-Du-Anh-Dau.lrc',
            theme: '#acf249',
        },
        {
            name: 'Đau Ở Đây Này!',
            artist: 'Nal',
            url: 'https://dl.dropboxusercontent.com/s/5928q56ifbcnaij/Dau-O-Day-Nay.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/oz9n0xfqdqxmmoe/Dau-O-Day-Nay.lrc',
            theme: '#ce7f16',
        },
        {
            name: 'Ai Chung Tình Được Mãi',
            artist: 'Đinh Tùng Huy',
            url: 'https://dl.dropboxusercontent.com/s/jia6edruuxjbzt6/Ai-Chung-Tinh-Duoc-Mai-Dinh-Tung-Huy.mp3',
            cover: 'https://i.imgur.com/pnZystG.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/9o0yhxfqrbud1z0/Ai-Chung-Tinh-Duoc-Mai.lrc',
            theme: '#128c88',
        },
        {
            name: 'Anh Vẫn Ở Đây',
            artist: 'Thành Đạt',
            url: 'https://dl.dropboxusercontent.com/s/xwe5agj0t02yrvp/Anh-Van-O-Day-Thanh-Dat.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            lrc: 'https://dl.dropboxusercontent.com/s/0vy4j7f7c0zv0nx/Anh-Van-O-Day.lrc',
            theme: '#4ba80a',
        },
        {
            name: 'Em Yêu Anh Ta',
            artist: 'Quốc Anh',
            url: 'https://dl.dropboxusercontent.com/s/flxx32m9af403v1/Em-Yeu-Anh-Ta-Quoc-Anh.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            lrc: 'https://dl.dropboxusercontent.com/s/jdq47smbzvse6ht/Em-Yeu-Anh-Ta.lrc',
            theme: '#f43508',
        },
        {
            name: 'Có Người Chờ Em',
            artist: 'Đào Duy Quý, Cầm',
            url: 'https://dl.dropboxusercontent.com/s/xr6l59n7emf5kmd/Co-Nguoi-Can-Em-Dao-Duy-Quy-Cam.mp3',
            cover: 'https://i.imgur.com/wZNgIxT.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/pf8gqprc6ofdc5s/Co-Nguoi-Cho-Em.lrc',
            theme: '#6bd4fc',
        },
        {
            name: 'Không Bằng',
            artist: 'Na',
            url: 'https://dl.dropboxusercontent.com/s/q1wdirsx59c40w2/Khong-Bang-Na.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            lrc: 'https://dl.dropboxusercontent.com/s/il13md5qxe553bb/Khong-Bang.lrc',
            theme: '#f981ca',
        },
        {
            name: 'Phai Nhòa Cảm Xúc',
            artist: 'Mr Siro',
            url: 'https://dl.dropboxusercontent.com/s/u933rl9m5pvakg2/Phai-Nhoa-Cam-Xuc-Mr-Siro.mp3',
            cover: 'https://i.imgur.com/9Mf5CA5.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/k7z4re3tv7qovmh/Phai-Nhoa-Cam-Xuc.lrc',
            theme: '#030497',
        },
        {
            name: 'Đọc Đúng Sách, Yêu Đúng Cách',
            artist: 'Anh Rồng',
            url: 'https://dl.dropboxusercontent.com/s/1zt40wnrtptkycg/Doc-Dung-Sach-Yeu-Dung-Cach-Anh-Rong.mp3',
            cover: 'https://i.imgur.com/nMNELgp.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/o7qmgcz1bq8ej6g/Doc-Dung-Sach-Yeu-Dung-Cach.lrc',
            theme: '#80ec73',
        },
        {
            name: 'Chưa Bao Giờ Em Quên',
            artist: 'Hương Ly',
            url: 'https://dl.dropboxusercontent.com/s/9vhuqx0xgiisn8m/Chua-Bao-Gio-Em-Quen-Huong-Ly.mp3',
            cover: 'https://i.imgur.com/dkeQ2li.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/xxi9qwenttxywjx/Chua-Bao-Gio-Em-Quen.lrc',
            theme: '#a50e92',
        },
        {
            name: 'Anh Cũng Biết Đau Biết Buồn',
            artist: 'Trịnh Thiên Ân',
            url: 'https://dl.dropboxusercontent.com/s/6mi69e4ztwukeyu/Anh-Cung-Biet-Dau-Biet-Buon-Trinh-Thien-An.mp3',
            cover: 'https://i.imgur.com/Ey9MsiX.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/d4jwhz76wqz2xik/Anh-Cung-Biet-Dau-Biet-Buon.lrc',
            theme: '#53f67e',
        },
        {
            name: 'Tan Vỡ',
            artist: 'Chi Dân',
            url: 'https://dl.dropboxusercontent.com/s/mq8z275srl2ltoo/Tan-Vo-Chi-Dan.mp3',
            cover: 'https://i.imgur.com/RZSKy1w.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/u03ht2tm3q1o1or/Tan-Vo.lrc',
            theme: '#5918ef',
        },
        {
            name: 'Câu Hứa Chưa Vẹn Tròn',
            artist: 'Phát Huy T4',
            url: 'https://dl.dropboxusercontent.com/s/mwutb3sy474wlrw/Cau-Hua-Chua-Ven-Tron-Phat-Huy-T4.mp3',
            cover: 'https://i.imgur.com/qJ6zA8N.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/9b89psmfy1lfhd5/Cau-Hua-Chua-Ven-Tron.lrc',
            theme: '#01843d',
        },
        {
            name: 'Bao Lâu Ta Lại Yêu Một Người',
            artist: 'Doãn Hiếu',
            url: 'https://dl.dropboxusercontent.com/s/s4updyzagvn1yip/Bao-Lau-Ta-Lai-Yeu-Mot-Nguoi-Doan-Hieu.mp3',
            cover: 'https://i.imgur.com/NCvyvpR.jpg',
            theme: '#2dc638',
        },
        {
            name: 'Thay Lòng',
            artist: 'Nal, VTK',
            url: 'https://dl.dropboxusercontent.com/s/yhixjkbf5rym3wg/Thay-Long-Nal-VTK.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            theme: '#4c2c7d',
        },
        {
            name: 'Anh Lại Làm Em Khóc',
            artist: 'Bảo Yến Rosie',
            url: 'https://dl.dropboxusercontent.com/s/frnlz5jqc2cnwhg/Anh-Lai-Lam-Em-Khoc-Bao-Yen-Rosie.mp3',
            cover: 'https://i.imgur.com/z73Cn5P.jpg',
            theme: '#6f7f3d',
        },
        {
            name: 'Đông Phai Mờ Dáng Ai',
            artist: 'DatKaa',
            url: 'https://dl.dropboxusercontent.com/s/kb0wnlhq4e9y9wy/Dong-Phai-Mo-Dang-Ai-DatKaa.mp3',
            cover: 'https://i.imgur.com/dYYqCwE.jpg',
            theme: '#a695ed',
        },
        {
            name: 'Em Là Con Thuyền Cô Đơn',
            artist: 'Thái Học',
            url: 'https://dl.dropboxusercontent.com/s/igxtby9jaw8zidc/Em-La-Con-Thuyen-Co-Don-Thai-Hoc.mp3',
            cover: 'https://i.imgur.com/ZFL7rqa.jpg',
            theme: '#e6df61',
        },
        {
            name: 'Suy Nghĩ Trong Anh',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/zjjcjuf6srydacy/Suy-Nghi-Trong-Anh-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#137618',
        },
        {
            name: 'Bức Tranh Trắng Xóa',
            artist: 'K-ICM',
            url: 'https://dl.dropboxusercontent.com/s/duz0nmaqevkmmy7/Buc-Tranh-Trang-Xoa-K-ICM.mp3',
            cover: 'https://i.imgur.com/t2EjlRW.jpg',
            theme: '#520e6b',
        },
        {
            name: 'Người Lạ Thoáng Qua',
            artist: 'Đinh Tùng Huy',
            url: 'https://dl.dropboxusercontent.com/s/55ip4454477qdjl/Nguoi-La-Thoang-Qua-Dinh-Tung-Huy.mp3',
            cover: 'https://i.imgur.com/pnZystG.jpg',
            theme: '#75f40d',
        },
        {
            name: 'Tình Thương Phu Thê (Cover)',
            artist: 'Thái Học',
            url: 'https://dl.dropboxusercontent.com/s/lljrdro1irjvbrp/Tinh-Thuong-Phu-The-Thai-Hoc.mp3',
            cover: 'https://i.imgur.com/ZFL7rqa.jpg',
            theme: '#c16587',
        },
        {
            name: 'Khuê Mộc Lang',
            artist: 'Hương Ly, Jombie',
            url: 'https://dl.dropboxusercontent.com/s/st3dpy2w9zaqteb/Khue-Moc-Lang-Huong-Ly-Jombie.mp3',
            cover: 'https://i.imgur.com/dkeQ2li.jpg',
            theme: '#4c5999',
        },
        {
            name: 'Tình Xa Lúc Ban Chiều',
            artist: 'K-ICM',
            url: 'https://dl.dropboxusercontent.com/s/zdtryvchs5d1xlo/Tinh-Xa-Luc-Ban-Chieu-K-ICM.mp3',
            cover: 'https://i.imgur.com/t2EjlRW.jpg',
            theme: '#ac00f9',
        },
        {
            name: 'Sau Ngày Mưa',
            artist: 'Quang Đăng Trần',
            url: 'https://dl.dropboxusercontent.com/s/olmnxzsnamd6r31/Sau-Ngay-Mua-Quang-Dang-Tran.mp3',
            cover: 'https://i.imgur.com/oR7n5SK.jpg',
            theme: '#47030e',
        },
        {
            name: 'Sai Cách Yêu',
            artist: 'Lê Bảo Bình',
            url: 'https://dl.dropboxusercontent.com/s/f33bmn68jlls11j/Sai-Cach-Yeu-Le-Bao-Binh.mp3',
            cover: 'https://i.imgur.com/pQ1r8G2.jpg',
            theme: '#91d3b8',
        },
        {
            name: 'Đoạn Tuyệt Nàng Đi',
            artist: 'Phát Huy T4',
            url: 'https://dl.dropboxusercontent.com/s/2tszwyr9lzu2pnu/Doan-Tuyet-Nang-Di-Phat-Huy-T4.mp3',
            cover: 'https://i.imgur.com/qJ6zA8N.jpg',
            theme: '#5e7de3',
        },
        {
            name: 'Rồi Tới Luôn',
            artist: 'Nal',
            url: 'https://dl.dropboxusercontent.com/s/rwlxo5k7he4wnw2/Roi-Toi-Luon-Nal.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            theme: '#7f36fc',
        },
        {
            name: 'Chiều Đồng Quê',
            artist: 'H2K',
            url: 'https://dl.dropboxusercontent.com/s/ggkhp8qs1dy3n24/Chieu-Dong-Que-H2K.mp3',
            cover: 'https://i.imgur.com/XS4NU8Q.jpg',
            theme: '#50121c',
        },
        {
            name: 'Đau Hơn Chữ Đau',
            artist: 'Phạm Nguyên Ngọc',
            url: 'https://dl.dropboxusercontent.com/s/u03osv5n20xwu8q/Dau-Hon-Chu-Dau-Pham-Nguyen-Ngoc.mp3',
            cover: 'https://i.imgur.com/0Svzikp.jpg',
            theme: '#daa603',
        },
        {
            name: 'Sao Ta Ngược Lối',
            artist: 'Đình Dũng',
            url: 'https://dl.dropboxusercontent.com/s/bkjuzswhshmsjy7/Sao-Ta-Nguoc-Loi-Dinh-Dung.mp3',
            cover: 'https://i.imgur.com/wmftqnD.jpg',
            theme: '#11e757',
        },
        {
            name: 'Đừng Chúc Anh Hạnh Phúc',
            artist: 'La Hoàng Phúc',
            url: 'https://dl.dropboxusercontent.com/s/d7fga971ey9lj7p/Dung-Chuc-Anh-Hanh-Phuc-La-Hoang-Phuc.mp3',
            cover: 'https://i.imgur.com/Eo5CVRi.jpg',
            theme: '#e15481',
        },
        {
            name: 'Tuyệt Tình Ca',
            artist: 'Chú Hàng Xóm',
            url: 'https://dl.dropboxusercontent.com/s/ayhn8tsdllb1589/Tuyet-Tinh-Ca-Anh-Hang-Xom.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            theme: '#d08947',
        },
        {
            name: 'Em Nào Có Tội',
            artist: 'Thương Võ',
            url: 'https://dl.dropboxusercontent.com/s/4ojw6ul4776ieku/Em-Nao-Co-Toi-Thuong-Vo.mp3',
            cover: 'https://i.imgur.com/HYDm8yl.jpg',
            theme: '#4405ce',
        },
        {
            name: 'Phải Giữ Em Thế Nào',
            artist: 'Mr Siro',
            url: 'https://dl.dropboxusercontent.com/s/tqmygpa02pz2gly/Phai-Giu-Em-The-Nao-Mr-Siro.mp3',
            cover: 'https://i.imgur.com/9Mf5CA5.jpg',
            theme: '#de25e5',
        },
        {
            name: 'Anh Thề Đấy',
            artist: 'Thanh Hưng',
            url: 'https://dl.dropboxusercontent.com/s/6xlsroujrpr9tvt/Anh-The-Day-Thanh-Hung.mp3',
            cover: 'https://i.imgur.com/Jq5iCzV.jpg',
            theme: '#706195',
        },
        {
            name: 'Em Sẽ Là Người Ra Đi (Ver 2021)',
            artist: 'Cẩm Ly',
            url: 'https://dl.dropboxusercontent.com/s/c54j7w7ts923xeb/Em-Se-La-Nguoi-Ra-Di-Ver-2021-Cam-Ly.mp3',
            cover: 'https://i.imgur.com/W95yCm2.jpg',
            theme: '#81bfc9',
        },
        {
            name: 'Quên Một Người Thật Khó',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/cwlavywczp7gga7/Quen-Mot-Nguoi-That-Kho-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#d0cd94',
        },
        {
            name: 'Phận Duyên Lỡ Làng',
            artist: 'Phát Huy T4, Truzg',
            url: 'https://dl.dropboxusercontent.com/s/yw2tca85hwyq45w/Phan-Duyen-Lo-Lang-Phat-Huy-T4-Truzg.mp3',
            cover: 'https://i.imgur.com/qJ6zA8N.jpg',
            theme: '#d1a1d5',
        },
        {
            name: 'Cô Đơn Dành Cho Ai',
            artist: 'Nal, Lee Ken',
            url: 'https://dl.dropboxusercontent.com/s/1nc9bk1eavps6kf/Co-Don-Danh-Cho-Ai.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            theme: '#ae0671',
        },
        {
            name: 'Rồi Mình Sẽ Hạnh Phúc',
            artist: 'Tuyền June',
            url: 'https://dl.dropboxusercontent.com/s/qjovywj13mdn3x9/Roi-Minh-Se-Hanh-Phuc-Tuyen-June.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            theme: '#126d68',
        },
        {
            name: 'Mashup Bài Hát Hay Tiktok',
            artist: 'Changmie, Tiến Tới',
            url: 'https://dl.dropboxusercontent.com/s/sle3umhpj8fxhve/Mashup-Bai-Hat-Hot-Tiktok-Changmie-Tien-Toi.mp3',
            cover: 'https://i.imgur.com/I6XX75I.jpg',
            theme: '#d8d703',
        },
        {
            name: 'Càng Cố Chấp Càng Đau',
            artist: 'Yuki Huy Nam',
            url: 'https://dl.dropboxusercontent.com/s/y00y54c0n98h9jj/Cang-Co-Chap-Cang-Dau-Yuki-Huy-Nam.mp3',
            cover: 'https://i.imgur.com/w6A4d5g.jpg',
            theme: '#a61279',
        },
        {
            name: 'Phiến Lá Tĩnh Lặng',
            artist: 'Thuỳ Chi',
            url: 'https://dl.dropboxusercontent.com/s/0koo1ppko0hr5mu/Phien-La-Tinh-Lang-Thuy-Chi.mp3',
            cover: 'https://i.imgur.com/xZtXmQJ.png',
            theme: '#c2b35d',
        },
        {
            name: 'Người Muốn Yêu, KMB 2',
            artist: 'Phong Hạo, Báo Tay Band',
            url: 'https://dl.dropboxusercontent.com/s/z5vx758oqg9r7qm/Nguoi-Muon-Yeu-Ke-Muon-Buong-Phong-Hao-Bao-Tay-Band.mp3',
            cover: 'https://i.imgur.com/AifCam8.jpg',
            theme: '#4829e8',
        },
        {
            name: 'Lệ Duyên Tình',
            artist: 'Long Nón Lá',
            url: 'https://dl.dropboxusercontent.com/s/06sb5ranvak3rpi/Le-Duyen-Tinh-Long-Non-La-K-ICM.mp3',
            cover: 'https://i.imgur.com/MO6h4hp.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/6fndla5puye488o/Le-Duyen-Tinh.lrc',
            theme: '#5fe6f5',
        },
        {
            name: 'Xin Một Lần Được Yêu',
            artist: 'Hà An',
            url: 'https://dl.dropboxusercontent.com/s/8ddwec1rgit4qx9/Xin-Mot-Lan-Duoc-Yeu-Ha-An.mp3',
            cover: 'https://i.imgur.com/QcEMXBW.jpg',
            theme: '#8172c5',
        },
        {
            name: 'Sài Gòn Đau Lòng Quá',
            artist: 'Hứa Kim Tuyền, HD',
            url: 'https://dl.dropboxusercontent.com/s/bnw91cebpkqea84/Sai-Gon-Dau-Long-Qua-Hua-Kim-Tuyen-Hoang-Duyen.mp3',
            cover: 'https://i.imgur.com/bil3tPf.jpg',
            theme: '#018883',
        },
        {
            name: 'Hạ Còn Vương Nắng',
            artist: 'DatKaa',
            url: 'https://dl.dropboxusercontent.com/s/p22i0xzj766rgaa/Ha-Con-Vuong-Nang-DatKaa.mp3',
            cover: 'https://i.imgur.com/dYYqCwE.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/6u7ykq0m11cs3ns/Ha-Con-Vuong-Nang.lrc',
            theme: '#22fe4c',
        },
        {
            name: 'Anh Không Là Ánh Dương',
            artist: 'Trịnh Thiên Ân',
            url: 'https://dl.dropboxusercontent.com/s/v9ailcz56u0af0g/Anh-Khong-La-Anh-Duong-Trinh-Thien-An.mp3',
            cover: 'https://i.imgur.com/Ey9MsiX.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/i7e9b5x48vq8le8/Anh-Khong-La-Anh-Duong.lrc',
            theme: '#2b5be7',
        },
        {
            name: 'Ngàn Yêu Thương Về Đâu',
            artist: 'Huy Vạc',
            url: 'https://dl.dropboxusercontent.com/s/t5rv3ujdvkh0qza/Ngan-Yeu-Thuong-Ve-Dau-Huy-Vac.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            theme: '#108a04',
        },
        {
            name: 'Yêu Thêm Lần 2 Lại Sai',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/ekfbunw1g3x26lk/Yeu-Them-Lan-2-Lai-Sai-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#c9e19c',
        },
        {
            name: 'Tình Bạn Diệu Kỳ',
            artist: 'Amee, Ricky Star, Lăng LD',
            url: 'https://dl.dropboxusercontent.com/s/rjhyv4d8gp5yvsr/Tinh-Ban-Dieu-Ky-Amee.mp3',
            cover: 'https://i.imgur.com/7MKQEaL.jpg',
            theme: '#6b2bb5',
        },
        {
            name: 'Họ Yêu Ai Mất Rồi',
            artist: 'Doãn Hiếu',
            url: 'https://dl.dropboxusercontent.com/s/r9ya2i74zb5g553/Ho-Yeu-Ai-Mat-Roi-Doan-Hieu.mp3',
            cover: 'https://i.imgur.com/NCvyvpR.jpg',
            theme: '#f32bd4',
        },
        {
            name: 'Quên Cách Yêu Thay Cách Nhớ',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/i5npq4ulxt6edvq/Quen-Cach-Yeu-Thay-Cach-Nho-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#bd9380',
        },
        {
            name: 'Chỉ Là Không Cùng Nhau (Live)',
            artist: 'Tăng Phúc, TTN',
            url: 'https://dl.dropboxusercontent.com/s/s5s8rl2sarp9d71/Chi-La-Khong-Cung-Nhau-Tang-Phuc-Truong-Thao-Nhi.mp3',
            cover: 'https://i.imgur.com/tvseqZN.jpg',
            theme: '#96abb7',
        },
        {
            name: 'Hạnh Phúc Không Đến Hai Lần',
            artist: 'LaLa Trần',
            url: 'https://dl.dropboxusercontent.com/s/60tuob52unh28sn/Hanh-Phuc-Khong-Den-Hai-Lan-LaLa-Tran.mp3',
            cover: 'https://i.imgur.com/265CPJh.jpg',
            theme: '#31c2ca',
        },
        {
            name: 'Từng Coi Là Tất Cả',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/4y84o5thxzogeku/Tung-Coi-La-Tat-Ca-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#165392',
        },
        {
            name: 'Hóa Tương Tư (Remix)',
            artist: 'Anh Rồng',
            url: 'https://dl.dropboxusercontent.com/s/5iglhhyrgs1o3jm/Hoa-Tuong-Tu-Remix-Anh-Rong.mp3',
            cover: 'https://i.imgur.com/nMNELgp.jpg',
            theme: '#347b63',
        },
        {
            name: 'Hình Xăm Khắc Trong Tim',
            artist: 'Phan Duy Anh',
            url: 'https://dl.dropboxusercontent.com/s/wvga3l8x1dfkx5p/Hinh-Xam-Khac-Trong-Tim-Phan-Duy-Anh.mp3',
            cover: 'https://i.imgur.com/JvWXlzJ.png',
            theme: '#913f67',
        },
        {
            name: 'Chỉ Muốn Bên Em Lúc Này',
            artist: 'Huy Vạc, JiKi X',
            url: 'https://dl.dropboxusercontent.com/s/mmakatuw9kwol81/Chi-Muon-Ben-Em-Luc-Nay-Huy-Vac.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            theme: '#7b69d5',
        },
        {
            name: 'Người Anh Yêu Nhất',
            artist: 'Đinh Đại Vũ',
            url: 'https://dl.dropboxusercontent.com/s/t3b2vncm29uft2u/Nguoi-Anh-Yeu-Nhat-Dinh-Dai-Vu.mp3',
            cover: 'https://i.imgur.com/moWLFSD.jpg',
            theme: '#9ac47f',
        },
        {
            name: 'Không Muốn Yêu Lại Càng Say Đắm',
            artist: 'Mr Siro',
            url: 'https://dl.dropboxusercontent.com/s/2r983tc3bg2vaf8/Khong-Muon-Yeu-Lai-Cang-Say-Dam-Mr-Siro.mp3',
            cover: 'https://i.imgur.com/9Mf5CA5.jpg',
            theme: '#a57b3a',
        },
        {
            name: 'Mashup NNHH & MNMN',
            artist: 'Vicky Nhung, Tố Ny',
            url: 'https://dl.dropboxusercontent.com/s/h3iuj7haddllsgh/Mashup-Ngoi-Nha-Hoa-Hong-Moi-Nguoi-Mot-Noi-Vicky-Nhung-To-Ny.mp3',
            cover: 'https://i.imgur.com/V7pda6M.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/j3g91xw0n8u1o9y/mashup-ngoi-nha-hoa-hong-moi-nguoi-mot-noi.lrc',
            theme: '#85b17f',
        },
        {
            name: 'Đom Đóm',
            artist: 'Jack',
            url: 'https://dl.dropboxusercontent.com/s/9qeap0r0k15xq1c/Dom-Dom-Jack.mp3',
            cover: 'https://i.imgur.com/4HoysrT.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/fig3m9ac2gajbfm/dom-dom.lrc',
            theme: '#3c4f6e',
        },
        {
            name: 'Chúng Ta Của Hiện Tại',
            artist: 'Sơn Tùng M-TP',
            url: 'https://dl.dropboxusercontent.com/s/9l9h7gog23e9ozv/Chung-Ta-Cua-Hien-Tai-Son-Tung-M-TP.mp3',
            cover: 'https://i.imgur.com/e2t2PEX.jpg',
            theme: '#c0897e',
        },
        {
            name: 'Sợ Lắm 2',
            artist: 'NB3 Hoài Bảo, Freak D',
            url: 'https://dl.dropboxusercontent.com/s/w517qoujlsb4o8f/so-lam-2-nb3-hoai-bao.mp3',
            cover: 'https://i.imgur.com/nK5R2GZ.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/v6fhryodp1syp82/so-lam-2.lrc',
            theme: '#031fd9',
        },
        {
            name: 'Níu Duyên',
            artist: 'Lê Bảo Bình',
            url: 'https://dl.dropboxusercontent.com/s/cmby4zwzraja3ra/Niu-Duyen-Le-Bao-Binh.mp3',
            cover: 'https://i.imgur.com/pQ1r8G2.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/448c8ih688hif33/niu-duyen.lrc',
            theme: '#3ea0cb',
        },
        {
            name: 'Người Yêu Giản Đơn',
            artist: 'Chi Dân',
            url: 'https://dl.dropboxusercontent.com/s/bmxz2d6re54rs30/Nguoi-Yeu-Gian-Don-Chi-Dan.mp3',
            cover: 'https://i.imgur.com/RZSKy1w.jpg',
            lrc: '',
            theme: '#fa62cd',
        },
        {
            name: 'Yêu Một Người Bình Thường',
            artist: 'Vũ Duy Khánh',
            url: 'https://dl.dropboxusercontent.com/s/z7ywjz9u5mua9pa/Yeu-Mot-Nguoi-Binh-Thuong-Vu-Duy-Khanh.mp3',
            cover: 'https://i.imgur.com/287Zj5e.jpg',
            theme: '#d0dc30',
        },
        {
            name: 'Đau Để Trưởng Thành',
            artist: 'OnlyC',
            url: 'https://dl.dropboxusercontent.com/s/3qcthijjpw6p85c/Dau-De-Truong-Thanh-OnlyC.mp3',
            cover: 'https://i.imgur.com/3b2SaMr.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/8sigmvx248l5z7d/dau-de-truong-thanh.lrc',
            theme: '#3b2ccc',
        },
        {
            name: 'Khách Sang Đò',
            artist: 'Châu Khải Phong',
            url: 'https://dl.dropboxusercontent.com/s/cv8npzy6jcqavz8/Khach-Sang-Do-Chau-Khai-Phong.mp3',
            cover: 'https://i.imgur.com/rCPAeVf.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ihx4iid01xqditf/khach-sang-do.lrc',
            theme: '#f1b74c',
        },
        {
            name: 'Hạnh Phúc Bỏ Rơi Em',
            artist: 'Hương Ly',
            url: 'https://dl.dropboxusercontent.com/s/kq6naeemz8ncu3z/Hanh-Phuc-Bo-Roi-Em-Huong-Ly.mp3',
            cover: 'https://i.imgur.com/dkeQ2li.jpg',
            theme: '#48acdb',
        },
        {
            name: 'Anh Từng Cố Gắng',
            artist: 'Nhật Phong',
            url: 'https://dl.dropboxusercontent.com/s/u48u4y7m2jamipx/Anh-Tung-Co-Gang-Nhat-Phong.mp3',
            cover: 'https://i.imgur.com/b3jxy6i.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/u9zqjc1sg2isdh1/anh-tung-co-gang.lrc',
            theme: '#c9f1db',
        },
        {
            name: 'Khác Biệt To Lớn',
            artist: 'Trịnh Thăng Bình, Liz KC',
            url: 'https://dl.dropboxusercontent.com/s/kvm7o1blvji2c5m/Khac-Biet-To-Lon-Trinh-Thang-Binh-Liz-Kim-Cuong.mp3',
            cover: 'https://i.imgur.com/ccBDYB6.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/3nwvxo608r2p37d/khac-biet-to-lon.lrc',
            theme: '#201f95',
        },
        {
            name: 'Ai Đợi Mình Được Mãi',
            artist: 'Thanh Hưng',
            url: 'https://dl.dropboxusercontent.com/s/frkhf8dcmz4rsj7/Ai-Doi-Minh-Duoc-Mai-Thanh-Hung.mp3',
            cover: 'https://i.imgur.com/Jq5iCzV.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/6skhkzdxd776zvd/ai-doi-minh-duoc-mai.lrc',
            theme: '#114ea1',
        },
        {
            name: 'Kẹo Bông Gòn',
            artist: 'H2K, TRUNKY',
            url: 'https://dl.dropboxusercontent.com/s/39lit01xzkg47dd/Keo-Bong-Gon-H2K-TRUNKY.mp3',
            cover: 'https://i.imgur.com/XS4NU8Q.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/8z1pcq5n0w15mcx/keo-bong-gon.lrc',
            theme: '#85ed87',
        },
        {
            name: 'Người Lạ',
            artist: 'Liêu Chấn Hải',
            url: 'https://dl.dropboxusercontent.com/s/0a2m4d4yrn3nj66/Nguoi-La-Lieu-Chan-Hai.mp3',
            cover: 'https://i.imgur.com/iSjbdtt.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/0qhxrj6bj6m8zw8/nguoi-la.lrc',
            theme: '#d19d74',
        },
        {
            name: 'Vẫn Còn Có Anh Đây',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/w720m9fdy7lifnj/Van-Con-Co-Anh-Day-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ow57qfgc1u4uwe6/van-con-co-anh-day.lrc',
            theme: '#6e8433',
        },
        {
            name: 'Chạnh Lòng Thương Cô (No Rap)',
            artist: 'Huy Vạc',
            url: 'https://dl.dropboxusercontent.com/s/3a4dkbhp4v6omyg/Chanh-Long-Thuong-Co-Huy-Vac.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            theme: '#0c0285',
        },
        {
            name: 'Đừng Nói Lời Chia Tay KEVCY',
            artist: 'Châu Gia Kiệt',
            url: 'https://dl.dropboxusercontent.com/s/6hekcb9bbou6zna/Dung-Noi-Chia-Tay-Khi-Em-Van-Con-Yeu-Chau-Gia-Kiet.mp3',
            cover: 'https://i.imgur.com/YU8wCTt.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/sp1jjof77v0f4u8/dung-chia-tay-khi-em-van-con-yeu.lrc',
            theme: '#a058be',
        },
        {
            name: 'Thiên Hạ Hữu Tình Nhân',
            artist: 'Juky San',
            url: 'https://dl.dropboxusercontent.com/s/jbt6agbopbbppso/Thien-Ha-Huu-Tinh-Nhan-Juky-San.mp3',
            cover: 'https://i.imgur.com/hxHzERf.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/pcm7jj031vvyh6z/thien-ha-huu-tinh-nhan.lrc',
            theme: '#eefe48',
        },
        {
            name: 'Anh Sẽ Cố Quên',
            artist: 'Trương Ngôn',
            url: 'https://dl.dropboxusercontent.com/s/lpd7fvxaug6tjro/Anh-Se-Co-Quen-Truong-Ngon.mp3',
            cover: 'https://i.imgur.com/Wjwvxbv.jpg',
            theme: '#0dce3a',
        },
        {
            name: 'Tình Tan Như Mây',
            artist: 'Tăng Vinh Quang',
            url: 'https://dl.dropboxusercontent.com/s/9ltkz57azcwu6up/Tinh-Tan-Nhu-May-Tang-Vinh-Quang.mp3',
            cover: 'https://i.imgur.com/W6vv0JW.jpg',
            theme: '#334a27',
        },
        {
            name: 'Không Đáng Để Thương',
            artist: 'Đinh Tùng Huy',
            url: 'https://dl.dropboxusercontent.com/s/uq9r2s71v1cenyl/KhongDangDeThuong-DinhTungHuy.mp3',
            cover: 'https://i.imgur.com/pnZystG.jpg',
            theme: '#78f0f2',
        },
        {
            name: 'Yêu Có Gì Vui',
            artist: 'Sang Bùi',
            url: 'https://dl.dropboxusercontent.com/s/kwlwusxxdmd9yz6/Yeu-Co-Gi-Vui-Sang-Bui.mp3',
            cover: 'https://i.imgur.com/aXJZHLt.jpeg',
            theme: '#4a174a',
        },
        {
            name: 'Đường Quyền Tình Yêu',
            artist: 'DatKaa',
            url: 'https://dl.dropboxusercontent.com/s/udjwzubr224w3a2/Duong-Quyen-Tinh-Yeu-DatKaa.mp3',
            cover: 'https://i.imgur.com/dYYqCwE.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/3xlp88ywhfrc1qc/duong-quyen-tinh-yeu.lrc',
            theme: '#3a8b16',
        },
        {
            name: 'Em Băng Qua',
            artist: 'Lập Nguyên',
            url: 'https://dl.dropboxusercontent.com/s/t4zo9e7q0l8u49s/Em-Bang-Qua-Lap-Nguyen.mp3',
            cover: 'https://i.imgur.com/87HxuwQ.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ud94602dowqomcf/em-bang-qua.lrc',
            theme: '#9cdb44',
        },
        {
            name: 'Hoa Hải Đường',
            artist: 'Jack',
            url: 'https://dl.dropboxusercontent.com/s/5wpgal890dr5m6o/Hoa-Hai-Duong-Jack.mp3',
            cover: 'https://i.imgur.com/4HoysrT.jpg',
            theme: '#9ec038',
        },
        {
            name: 'Thế Thái',
            artist: 'Hương Ly',
            url: 'https://dl.dropboxusercontent.com/s/k4h1g9yw7h6hkm8/TheThai-HuongLy-6728509.mp3',
            cover: 'https://i.imgur.com/dkeQ2li.jpg',
            theme: '#d58ac1',
        },
        {
            name: 'Đừng Bỏ Mặc Anh Nhé',
            artist: 'Du Thiên',
            url: 'https://dl.dropboxusercontent.com/s/vpeiipsjak2o2y5/Dung-Bo-Mac-Anh-Nhe-Du-Thien.mp3',
            cover: 'https://i.imgur.com/Rmz8DtG.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ba8h1za2llwcq5z/dung-bo-mac-anh-nhe.lrc',
            theme: '#812be2',
        },
        {
            name: 'Em Về Sớm Thôi',
            artist: 'Huy Vạc, Thái Học',
            url: 'https://dl.dropboxusercontent.com/s/dfhgpktesx4j1kb/EmVeSomThoi-HuyVacThaiHoc.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            theme: '#d89907',
        },
        {
            name: 'Trên Tình Bạn Dưới Tình Yêu',
            artist: 'MIN',
            url: 'https://dl.dropboxusercontent.com/s/dwbd4sy02c0bpvh/Tren-Tinh-Ban-Duoi-Tinh-Yeu-Min.mp3',
            cover: 'https://i.imgur.com/6W3eUX3.jpg',
            theme: '#ae477d',
        },
        {
            name: 'Người Theo Gió Mây',
            artist: 'Acy Xuân Tài, Rum',
            url: 'https://dl.dropboxusercontent.com/s/ew7tbla7vlx13qi/Nguoi-Theo-Gio-May-Acy-Xuan-Tai-Rum.mp3',
            cover: 'https://i.imgur.com/rd4IW2e.jpg',
            theme: '#0d0c0e',
        },
        {
            name: 'Lãng Quên Chiều Thu',
            artist: 'Hoa Vinh',
            url: 'https://dl.dropboxusercontent.com/s/1abe4dmz0ygw580/Lang-Quen-Chieu-Thu-Hoa-Vinh.mp3',
            cover: 'https://i.imgur.com/tjmDIus.jpg',
            theme: '#262f9f',
        },
        {
            name: 'Điều Ước Cuối',
            artist: 'Hoàng Đạo',
            url: 'https://dl.dropboxusercontent.com/s/kjubq9u4vu6jfmi/Dieu-Uoc-Cuoi-Hoang-Dao.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            lrc: 'https://dl.dropboxusercontent.com/s/q26esik3j6hlnxo/dieu-uoc-cuoi.lrc',
            theme: '#ec9a2d',
        },
        {
            name: 'Thanh Xuân Của Anh VTLE',
            artist: 'Bằng Việt Nguyễn',
            url: 'https://dl.dropboxusercontent.com/s/1zris7kpbph1myv/Thanh-Xuan-Cua-Anh-Viet-Tat-La-Em-Bang-Viet-Nguyen.mp3',
            cover: 'https://i.imgur.com/KHJqT2W.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/h2ld2311dm6gif1/thanh-xuan-cua-anh-viet-tat-la-em.lrc',
            theme: '#c43512',
        },
        {
            name: 'Tháng Năm Không Quên',
            artist: 'H2K, TRUNKY',
            url: 'https://dl.dropboxusercontent.com/s/tb2c29cayj3jmg6/Thang-Nam-Khong-Quen-H2K-KN.mp3',
            cover: 'https://i.imgur.com/XS4NU8Q.jpg',
            theme: '#662269',
        },
        {
            name: 'Sóng Gió',
            artist: 'Jack',
            url: 'https://dl.dropboxusercontent.com/s/0kfllc50qmbo8ne/Song-Gio-Jack-K-ICM.mp3',
            cover: 'https://i.imgur.com/4HoysrT.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/oneoa9s68bfyitj/song-gio.lrc',
            theme: '#ceb125',
        },
        {
            name: 'Có Mới Nới Cũ',
            artist: 'Hồ Gia Khánh',
            url: 'https://dl.dropboxusercontent.com/s/h6b117s466nwdyd/Co-Moi-Noi-Cu-Ho-Gia-Khanh.mp3',
            cover: 'https://i.imgur.com/Ll7PdbR.jpg',
            theme: '#5e617f',
        },
        {
            name: 'Không Có Gì Là Mãi Mãi',
            artist: 'Kiun Gia Tuấn',
            url: 'https://dl.dropboxusercontent.com/s/whlqio3npx9opa6/Khong-Co-Gi-La-Mai-Mai-Kiun-Gia-Tuan.mp3',
            cover: 'https://i.imgur.com/20ovxS8.jpg',
            theme: '#eaa091',
        },
        {
            name: 'Kết Thúc Một Cuộc Tình',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/hesp0yipzxpafl5/Ket-Thuc-Mot-Cuoc-Tinh-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#35a210',
        },
        {
            name: 'Mất Người Anh Yêu (Solo Version)',
            artist: 'Khánh Won',
            url: 'https://dl.dropboxusercontent.com/s/hzhuumwwj1nhlt0/Mat-Nguoi-Anh-Yeu-Solo-Version-Khanh-Won.mp3',
            cover: 'https://i.imgur.com/YqUOn38.jpg',
            theme: '#f017f1',
        },
        {
            name: 'Buồn Làm Chi Em Ơi',
            artist: 'Hoài Lâm',
            url: 'https://dl.dropboxusercontent.com/s/6bzxit7dp1lnf25/Buon-Lam-Chi-Em-Oi-Hoai-Lam.mp3',
            cover: 'https://i.imgur.com/s8ZGqbN.jpg',
            theme: '#4119c8',
        },
        {
            name: 'Không Lấy Được Vợ',
            artist: 'Hồ Gia Khánh',
            url: 'https://dl.dropboxusercontent.com/s/igveipf9ixxkhrc/Khong-Lay-Duoc-Vo-Ho-Gia-Khanh.mp3',
            cover: 'https://i.imgur.com/Ll7PdbR.jpg',
            theme: '#2d5142',
        },
        {
            name: 'Đã Từng Bên Nhau',
            artist: 'NQP',
            url: 'https://dl.dropboxusercontent.com/s/q2l7i0fwofwgvf6/Da-Tung-Ben-Nhau-NQP.mp3',
            cover: 'https://i.imgur.com/XeKf2ez.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/ebwbv2l6ao134ts/Da-Tung-Ben-Nhau.lrc',
            theme: '#839030',
        },
        {
            name: 'Bạc Phận',
            artist: 'Jack',
            url: 'https://dl.dropboxusercontent.com/s/v6sejz9ytnzr71p/Bac-Phan-Jack-K-ICM.mp3',
            cover: 'https://i.imgur.com/4HoysrT.jpg',
            theme: '#324895',
        },
        {
            name: 'Đừng Quên Tên Anh',
            artist: 'Hoa Vinh',
            url: 'https://dl.dropboxusercontent.com/s/wixs2gzwe790lll/Dung-Quen-Ten-Anh-Hoa-Vinh.mp3',
            cover: 'https://i.imgur.com/tjmDIus.jpg',
            theme: '#ac999f',
        },
        {
            name: 'Biết Đau Nhưng Vẫn Yêu',
            artist: 'Hồ Gia Khánh',
            url: 'https://dl.dropboxusercontent.com/s/h5hcvp0vgvx10cw/Biet-Dau-Nhung-Van-Yeu-Ho-Gia-Khanh.mp3',
            cover: 'https://i.imgur.com/Ll7PdbR.jpg',
            theme: '#af94e0',
        },
        {
            name: 'Điều Thật Lòng Nhất',
            artist: 'Hoài Ly',
            url: 'https://dl.dropboxusercontent.com/s/d73lco2fi17kkkg/dieuthatlongnhat.mp3',
            cover: 'https://i.imgur.com/PtR1GHe.jpg',
            theme: '#ca6e6b',
        },
        {
            name: 'Hãy Vì Anh Đừng Khóc',
            artist: 'Nguyễn Đình Vũ',
            url: 'https://dl.dropboxusercontent.com/s/f52t7lbotwklma3/Hay-Vi-Anh-Dung-Khoc-Nguyen-Dinh-Vu.mp3',
            cover: 'https://i.imgur.com/nbhcYYh.jpg',
            theme: '#57b097',
        },
        {
            name: 'Thay Thế',
            artist: 'Hồ Gia Hùng',
            url: 'https://dl.dropboxusercontent.com/s/kj3jnk78t9agald/Thay-The-Ho-Gia-Hung.mp3',
            cover: 'https://imgur.com/c4yGSZi.jpg',
            theme: '#ae3fc5',
        },
        {
            name: 'Người Thứ 3',
            artist: 'H2K, TRUNKY',
            url: 'https://dl.dropboxusercontent.com/s/bex3j6qbbzicrki/Nguoi-Thu-3-H2K-KN.mp3',
            cover: 'https://i.imgur.com/XS4NU8Q.jpg',
            theme: '#7d996c',
        },
        {
            name: 'Em Ơi Lên Phố',
            artist: 'Minh Vương M4U',
            url: 'https://dl.dropboxusercontent.com/s/jrazficy3mqhc0x/Em-Oi-Len-Pho-Minh-Vuong-M4U.mp3',
            cover: 'https://i.imgur.com/PCzwbAw.jpg',
            theme: '#a47253',
        },
        {
            name: 'Đâu Còn Đây',
            artist: 'Nal, Lee Ken',
            url: 'https://dl.dropboxusercontent.com/s/u73immdnpmjq5jp/Dau-Con-Day-Lee-Ken-Nal.mp3',
            cover: 'https://i.imgur.com/2nf7zg4.jpg',
            theme: '#1e1efb',
        },
        {
            name: 'Khóc Cho Người Ai Khóc Cho Anh',
            artist: 'Gia Huy Singer',
            url: 'https://dl.dropboxusercontent.com/s/ayx1lxr4jxx0fof/Khoc-Cho-Nguoi-Ai-Khoc-Cho-Anh-Gia-Huy-Singer.mp3',
            cover: 'https://i.imgur.com/AU8XnLE.jpg',
            theme: '#65d20d',
        },
        {
            name: 'Bước Qua Đời Nhau',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/ps06ptn32dtp9ve/Buoc-Qua-Doi-Nhau-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#cfb718',
        },
        {
            name: 'Ai Thật Lòng Thương Em (Cover)',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/4bygvuoo1ox0nxx/Ai-That-Long-Thuong-Em-Cao-Nam-Thanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#cee6a0',
        },
        {
            name: '1 Phút',
            artist: 'Andiez',
            url: 'https://dl.dropboxusercontent.com/s/nx0y6l8fm501q2z/1-Phut-Andiez.mp3',
            cover: 'https://i.imgur.com/3ItwjVb.jpg',
            theme: '#b58175',
        },
        {
            name: 'Người Ấy',
            artist: 'Trịnh Thăng Bình',
            url: 'https://dl.dropboxusercontent.com/s/6u7fgdtk670dybf/Nguoi-Ay-Trinh-Thang-Binh.mp3',
            cover: 'https://i.imgur.com/ccBDYB6.jpg',
            theme: '#3f5a36',
        },
        {
            name: 'Đừng Yêu Nữa, Em Mệt Rồi',
            artist: 'MIN',
            url: 'https://dl.dropboxusercontent.com/s/j0m66dtidxdna3y/Dung-Yeu-Nua-Em-Met-Roi-MIN.mp3',
            cover: 'https://i.imgur.com/6W3eUX3.jpg',
            theme: '#627c18',
        },
        {
            name: 'Tâm Sự Với Người Lạ',
            artist: 'Tiên Cookie',
            url: 'https://dl.dropboxusercontent.com/s/reoe8p7o6ct80qv/Tam-Su-Voi-Nguoi-La-Tien-Cookie.mp3',
            cover: 'https://i.imgur.com/FFSZCjt.jpg',
            theme: '#e4e067',
        },
        {
            name: 'Nhạt Vài Lần',
            artist: 'Sĩ Hùng Jiki',
            url: 'https://dl.dropboxusercontent.com/s/nl5dkdgrqv7mdby/Nhat-Vai-Lan-Si-Hung-Jiki.mp3',
            cover: 'https://i.imgur.com/WdU2xHs.jpg',
            theme: '#2cb58e',
        },
        {
            name: 'Sau Tất Cả',
            artist: 'Erik',
            url: 'https://dl.dropboxusercontent.com/s/i5vyrkq1vrr6hen/Sau-Tat-Ca-Erik.mp3',
            cover: 'https://i.imgur.com/QoV2LFG.jpg',
            theme: '#fa396f',
        },
        {
            name: 'Thiệp Hồng Người Dưng',
            artist: 'X2X',
            url: 'https://dl.dropboxusercontent.com/s/duirjmi7bc0taph/Thiep-Hong-Nguoi-Dung-X2X.mp3',
            cover: 'https://i.imgur.com/cQ8ZvBn.jpg',
            theme: '#314b7c',
        },
        {
            name: 'Em Gì Ơi',
            artist: 'Jack',
            url: 'https://dl.dropboxusercontent.com/s/j89g8oohf2x1g1y/Em-Gi-Oi-Jack-K-ICM.mp3',
            cover: 'https://i.imgur.com/4HoysrT.jpg',
            theme: '#cb9818',
        },
        {
            name: 'Chẳng Gì Đẹp Đẽ Trên Đời Mãi (Live)',
            artist: 'Khang Việt',
            url: 'https://dl.dropboxusercontent.com/s/skrq38vgfmvsr04/Chang-Gi-Dep-De-Tren-Doi-Mai-Live-Khang-Viet.mp3',
            cover: 'https://i.imgur.com/i9Bagt9.jpg',
            theme: '#b620c3',
        },
        {
            name: 'Chỉ Là Câu Hứa',
            artist: 'Đinh Tùng Huy',
            url: 'https://dl.dropboxusercontent.com/s/vlpw24iodnhaqws/Chi-La-Cau-Hua-Dinh-Tung-Huy.mp3',
            cover: 'https://i.imgur.com/pnZystG.jpg',
            theme: '#de1c55',
        },
        {
            name: 'Tìm Về Nơi Có Ánh Nắng Hoàng Hôn',
            artist: 'Huy Vạc',
            url: 'https://dl.dropboxusercontent.com/s/9n5si4dfm19q0s2/Tim-Ve-Noi-Co-Anh-Hoang-Hon-Huy-Vac.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            theme: '#060ead',
        },
        {
            name: 'Điều Anh Biết',
            artist: 'Chi Dân',
            url: 'https://dl.dropboxusercontent.com/s/dzi1v9ii72n6mhq/Dieu-Anh-Biet-Chi-Dan.mp3',
            cover: 'https://i.imgur.com/RZSKy1w.jpg',
            theme: '#b4d19c',
        },
        {
            name: 'Biết Em Chưa Thể Quên',
            artist: 'Trương Ngôn',
            url: 'https://dl.dropboxusercontent.com/s/r90w1w5bmfmfazv/Biet-Em-Chua-The-Quen-Truong-Ngon.mp3',
            cover: 'https://i.imgur.com/Wjwvxbv.jpg',
            theme: '#3965d4',
        },
        {
            name: 'Từng Yêu',
            artist: 'Phan Duy Anh',
            url: 'https://dl.dropboxusercontent.com/s/sgfpvrmalgrb7h2/Tung-Yeu-Phan-Duy-Anh.mp3',
            cover: 'https://i.imgur.com/JvWXlzJ.png',
            theme: '#b63c2b',
        },
        {
            name: 'Dừng Lại Đây Thôi',
            artist: 'Hoa Vinh',
            url: 'https://dl.dropboxusercontent.com/s/h80debm128xt1yc/Dung-Lai-Day-Thoi-Hoa-Vinh.mp3',
            cover: 'https://i.imgur.com/tjmDIus.jpg',
            theme: '#6c66a0',
        },
        {
            name: 'Anh Nói Em Nghe Đi',
            artist: 'Hoàng Yến Chibi',
            url: 'https://dl.dropboxusercontent.com/s/pg9sfv46f1rnzkr/AnhNoiEmNgheDiHoangYenChibi.mp3',
            cover: 'https://i.imgur.com/b6dHstH.jpg',
            theme: '#71b48a',
        },
        {
            name: 'Anh Thương Em, Em Thương Ai',
            artist: 'Đinh Tùng Huy',
            url: 'https://dl.dropboxusercontent.com/s/0n4tmv24uuogqiq/Anh-Thuong-Em-Em-Thuong-Ai-Dinh-Tung-Huy.mp3',
            cover: 'https://i.imgur.com/pnZystG.jpg',
            theme: '#0bca6d',
        },
        {
            name: 'Tình Sầu Thiên Thu Muôn Lối',
            artist: 'Võ Đình Hiếu',
            url: 'https://dl.dropboxusercontent.com/s/8jdukef73benyqt/TinhSauThienThuMuonLoi-VoDinhHieu.mp3',
            cover: 'https://i.imgur.com/voqmiJR.jpg',
            theme: '#0d817d',
        },
        {
            name: 'Ngôi Sao Của Anh',
            artist: 'Huy Vạc',
            url: 'https://dl.dropboxusercontent.com/s/oqzmafly28d30og/Ngoi-Sao-Cua-Anh-Huy-Vac.mp3',
            cover: 'https://i.imgur.com/gSGKxEP.jpg',
            theme: '#0aa134',
        },
        {
            name: 'Dành Cho Em',
            artist: 'Hoàng Tôn',
            url: 'https://dl.dropboxusercontent.com/s/mki9bj1zvaerlyp/Danh-Cho-Em-Hoang-Ton.mp3',
            cover: 'https://i.imgur.com/G0qqsGz.jpg',
            theme: '#c7bd0a',
        },
        {
            name: 'Mỉm Cười Cho Qua',
            artist: 'Hamlet Trương',
            url: 'https://dl.dropboxusercontent.com/s/ipvg599klx4cklf/Mim-Cuoi-Cho-Qua-Hamlet-Truong.mp3',
            cover: 'https://i.imgur.com/5z1JONm.jpg',
            theme: '#3a0139',
        },
        {
            name: 'Hơn Cả Yêu',
            artist: 'Đức Phúc',
            url: 'https://dl.dropboxusercontent.com/s/vw4ven5jjkp8kis/Hon-Ca-Yeu-Duc-Phuc.mp3',
            cover: 'https://i.imgur.com/twwtTvF.jpg',
            theme: '#e40359',
        },
        {
            name: 'Ai Khâu Nước Mắt',
            artist: 'Hoàng Đạo',
            url: 'https://dl.dropboxusercontent.com/s/b0xv6ctusgdqoxi/Ai-Khau-Nuoc-Mat-Hoang-Dao.mp3',
            cover: 'https://i.imgur.com/D7dA3Nx.png',
            theme: '#a60c3a',
        },
        {
            name: 'Khác Biệt',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/s2kxy9h5y6y7zac/Khac-Biet-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#588b54',
        },
        {
            name: 'Đừng Khóc Nữa Mà',
            artist: 'Gia Huy Singer',
            url: 'https://dl.dropboxusercontent.com/s/x6viwpo0riq0w6f/Dung-Khoc-Nua-Ma-Gia-Huy-Singer.mp3',
            cover: 'https://i.imgur.com/AU8XnLE.jpg',
            theme: '#492957',
        },
        {
            name: 'Ngỡ Như Giấc Mơ (Cover)',
            artist: 'Chu Duyên',
            url: 'https://dl.dropboxusercontent.com/s/tffri1607md5tz4/Ngo-Nhu-Giac-Mo-Chu-Duyen.mp3',
            cover: 'https://i.imgur.com/XUlfPMx.jpg',
            theme: '#91ad45',
        },
        {
            name: 'Hoa Nở Không Màu',
            artist: 'Hoài Lâm',
            url: 'https://dl.dropboxusercontent.com/s/lszfnn7h2gd367r/Hoa-Bo-Khong-Mau-Hoai-Lam.mp3',
            cover: 'https://i.imgur.com/s8ZGqbN.jpg',
            theme: '#3959d4',
        },
        {
            name: 'Đóa Quỳnh Lan',
            artist: 'YuniBoo, H2K',
            url: 'https://dl.dropboxusercontent.com/s/b55edxeh4s8hk3v/Doa-Quynh-Lan-YuniBoo-H2K.mp3',
            cover: 'https://i.imgur.com/P3BS8Jx.jpg',
            theme: '#6e2c1f',
        },
        {
            name: 'Anh Thương Em Còn Non Dại',
            artist: 'Đình Dũng',
            url: 'https://dl.dropboxusercontent.com/s/vyvrz0riqj5ncdt/Anh-Thuong-Em-Con-Non-Dai-Dinh-Dung.mp3',
            cover: 'https://i.imgur.com/wmftqnD.jpg',
            theme: '#3f31de',
        },
        {
            name: 'Ai Mang Cô Đơn Đi',
            artist: 'APJ',
            url: 'https://dl.dropboxusercontent.com/s/kq712l51o2b589o/Ai-Mang-Co-Don-Di-APJ-K-ICM.mp3',
            cover: 'https://i.imgur.com/PeW1GxI.jpg',
            theme: '#facd43',
        },
        {
            name: 'Đúng Cũng Thành Sai',
            artist: 'Mỹ Tâm',
            url: 'https://dl.dropboxusercontent.com/s/sinmfkdzacl8buh/Dung-Cung-Thanh-Sai-My-Tam.mp3',
            cover: 'https://i.imgur.com/2tCQQ38.jpg',
            theme: '#8290cf',
        },
        {
            name: 'Hôm Nay Em Cưới Rồi',
            artist: 'Khải Đăng',
            url: 'https://dl.dropboxusercontent.com/s/ywf1jfmwpe109ts/Hom-Nay-Em-Cuoi-Roi-Khai-Dang.mp3',
            cover: 'https://i.imgur.com/snp5i4R.jpg',
            theme: '#53c49f',
        },
        {
            name: 'Dừng Thương',
            artist: 'DatKaa',
            url: 'https://dl.dropboxusercontent.com/s/zz6imo2a9eoh3vw/Dung-Thuong-DatKaa.mp3',
            cover: 'https://i.imgur.com/dYYqCwE.jpg',
            theme: '#ed90fe',
        },
        {
            name: 'Hạnh Phúc Đó Em Không Có',
            artist: 'Lương Minh Trang',
            url: 'https://dl.dropboxusercontent.com/s/xo6y0lbqh6r1t3d/Hanh-Phuc-Do-Em-Khong-Co-Luong-Minh-Trang.mp3',
            cover: 'https://i.imgur.com/2fNjavP.jpg',
            theme: '#9766a2',
        },
        {
            name: 'Sai Lầm Của Anh',
            artist: 'Đình Dũng',
            url: 'https://dl.dropboxusercontent.com/s/wp1h61exleqptx1/Sai-Lam-Cua-Anh-Dinh-Dung.mp3',
            cover: 'https://i.imgur.com/wmftqnD.jpg',
            theme: '#1b227c',
        },
        {
            name: 'Công Dã Tràng',
            artist: 'Duy Phước, Sóc Nâu',
            url: 'https://dl.dropboxusercontent.com/s/7jvrcts7y9bzv9n/Cong-Da-Trang-Duy-Phuoc.mp3',
            cover: 'https://i.imgur.com/Y42uSse.jpg',
            theme: '#ef32f4',
        },
        {
            name: 'Thích Thì Đến',
            artist: 'Lê Bảo Bình',
            url: 'https://dl.dropboxusercontent.com/s/6vhlntam1lnbtdc/Thich-Thi-Den-Le-Bao-Binh.mp3',
            cover: 'https://i.imgur.com/pQ1r8G2.jpg',
            theme: '#352e73',
        },
        {
            name: 'Hai Chữ Đã Từng',
            artist: 'Như Việt',
            url: 'https://dl.dropboxusercontent.com/s/2jhg53mn002j17m/Hai-Chu-Da-Tung-Nhu-Viet.mp3',
            cover: 'https://i.imgur.com/4GefVhV.jpg',
            theme: '#5a4ad9',
        },
        {
            name: 'Bước Qua Đời Nhau',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/ps06ptn32dtp9ve/Buoc-Qua-Doi-Nhau-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#a3e0c7',
        },
        {
            name: 'Yêu Từ Đâu Mà Ra?',
            artist: 'Lil Zpoet',
            url: 'https://dl.dropboxusercontent.com/s/sdpi6piuid7mjmk/Yeu-Tu-Dau-Ma-Ra-Lil-Zpoet.mp3',
            cover: 'https://i.imgur.com/GzXbWoR.jpg',
            theme: '#d7e629',
        },
        {
            name: 'Yêu Một Người Tổn Thương',
            artist: 'Nhật Phong',
            url: 'https://dl.dropboxusercontent.com/s/64lutm3ve22tkak/Yeu-Mot-Nguoi-Ton-Thuong-Nhat-Phong.mp3',
            cover: 'https://i.imgur.com/b3jxy6i.jpg',
            theme: '#263fce',
        },
        {
            name: 'Cô Đơn Sẽ Tốt Hơn',
            artist: 'Lương Gia Hùng',
            url: 'https://dl.dropboxusercontent.com/s/hvpevlqq3z2yzq2/Co-Don-Se-Tot-Hon-Luong-Gia-Hung.mp3',
            cover: 'https://i.imgur.com/CqB81IB.jpg',
            theme: '#21b5a6',
        },
        {
            name: 'Cố Giang Tình',
            artist: 'X2X',
            url: 'https://dl.dropboxusercontent.com/s/n5spxz8aahr8bez/Co-Giang-Tinh-X2X.mp3',
            cover: 'https://i.imgur.com/cQ8ZvBn.jpg',
            theme: '#29de4f',
        },
        {
            name: 'Ngắm Hoa Lệ Rơi',
            artist: 'Châu Khải Phong',
            url: 'https://dl.dropboxusercontent.com/s/180r6autt64z6td/NgamHoaLeRoi-ChauKhaiPhong.mp3',
            cover: 'https://i.imgur.com/rCPAeVf.jpg',
            theme: '#c47cc1',
        },
        {
            name: 'Mashup Hoa Bằng Lăng (Cover)',
            artist: 'Jack Viet Nam, DT',
            url: 'https://dl.dropboxusercontent.com/s/gwsq215zk5lsllq/Mashup-Hoa-Bang-Lang-Cover-Jack-Viet-Nam-Duong-Tang.mp3',
            cover: 'https://i.imgur.com/HOJa0jv.jpg',
            theme: '#beab1f',
        },
        {
            name: 'Không Phải Anh Đúng Không',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/1n9iz3532cmv9i4/Khong-Phai-Anh-Dung-Khong-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#9c9b42',
        },
        {
            name: 'Bỏ Lỡ Một Người',
            artist: 'Lê Bảo Bình',
            url: 'https://dl.dropboxusercontent.com/s/l8pleuft757lhql/Bo-Lo-Mot-Nguoi-Le-Bao-Binh.mp3',
            cover: 'https://i.imgur.com/pQ1r8G2.jpg',
            theme: '#996456',
        },
        {
            name: 'Anh Chưa Đủ Tư Cách',
            artist: 'Lý Tuấn Kiệt',
            url: 'https://dl.dropboxusercontent.com/s/ilggcep57zm4o73/Anh-Chua-Du-Tu-Cach-Ly-Tuan-Kiet.mp3',
            cover: 'https://i.imgur.com/mXjxqxn.jpg',
            lrc: 'https://dl.dropboxusercontent.com/s/5gite486amgwtom/anh-chua-du-tu-cach.lrc',
            theme: '#c94591',
		
        },
        {
            name: 'Vết Đau',
            artist: 'Hoàng Gia Huy',
            url: 'https://dl.dropboxusercontent.com/s/aoj142qj6u8ou5w/Vet-Dau-Hoang-Gia-Huy.mp3',
            cover: 'https://i.imgur.com/45rFhF9.jpg',
            theme: '#89a5ce',
        },
        {
            name: 'Vì Anh Vô Tình',
            artist: 'The Men',
            url: 'https://dl.dropboxusercontent.com/s/4f8d8gch52cbpt9/Vi-Anh-Vo-Tinh-The-Men.mp3',
            cover: 'https://i.imgur.com/YjILcnQ.jpg',
            theme: '#7af800',
        },
        {
            name: 'Chiếc Nhẫn Ngày Xưa',
            artist: 'Jimmii Nguyễn',
            url: 'https://dl.dropboxusercontent.com/s/7pk2zs6opwj2dx4/chiec-nhan-ngay-xua.mp3',
            cover: 'https://i.imgur.com/WGtkWNL.jpg',
            theme: '#4248b2',
        },
        {
            name: 'Anh Không Muốn Ra Đi (Cover)',
            artist: 'Thế Phương VBK',
            url: 'https://dl.dropboxusercontent.com/s/o4qvrno4kzr2vfc/Anh-Khong-Muon-Ra-Di-Cover-The-Phuong-VBK.mp3',
            cover: 'https://i.imgur.com/MhIFAck.jpg',
            theme: '#7973c3',
        },
        {
            name: 'Tự Ngã Em Tự Đứng Lên',
            artist: 'Wendy Thảo',
            url: 'https://dl.dropboxusercontent.com/s/4d74ld7i9xx49p8/tungaemtudunglen.mp3',
            cover: 'https://i.imgur.com/V2HedSv.jpg',
            theme: '#0d17ea',
        },
        {
            name: 'Hẹn Kiếp Sau',
            artist: 'Khả Hiệp',
            url: 'https://dl.dropboxusercontent.com/s/epvyg2uoviuhcfc/Hen-Kiep-Sau-Kha-Hiep.mp3',
            cover: 'https://i.imgur.com/OgWpWtY.jpg',
            theme: '#0f48c9',
        },
        {
            name: 'Em Của Ngày Hôm Qua',
            artist: 'Sơn Tùng M-TP',
            url: 'https://dl.dropboxusercontent.com/s/87ipdt95kcujgvy/EmCuaNgayHomQuaSonTungMTP.mp3',
            cover: 'https://i.imgur.com/e2t2PEX.jpg',
            theme: '#3f1b91',
        },
        {
            name: 'Không Thể Làm Khác Được',
            artist: 'Trịnh Thiên Ân',
            url: 'https://dl.dropboxusercontent.com/s/js2evqk0eodv9he/khongthelamkhacduoc.mp3',
            cover: 'https://i.imgur.com/Ey9MsiX.jpg',
            theme: '#182c69',
        },
        {
            name: 'Có Được Không Em',
            artist: 'Chi Dân',
            url: 'https://dl.dropboxusercontent.com/s/jo9ctjdcnjr9nu0/coduockhongem.mp3',
            cover: 'https://i.imgur.com/RZSKy1w.jpg',
            theme: '#9f1bd1',
        },
        {
            name: 'Lời Anh Chưa Thể Nói',
            artist: 'Hàn Khởi',
            url: 'https://dl.dropboxusercontent.com/s/hwqqxp2lvjlta5y/loianhchuathenoi.mp3',
            cover: 'https://i.imgur.com/LRJcjaT.jpg',
            theme: '#5da80a',
        },
        {
            name: 'Nợ Ai Đó Cả Thế Giới',
            artist: 'Phạm Quỳnh Anh',
            url: 'https://dl.dropboxusercontent.com/s/203avl4byvs8k8d/noaidocathegioi.mp3',
            cover: 'https://i.imgur.com/lbStubi.jpg',
            theme: '#e5ba8d',
        },
        {
            name: 'Món Quà Vô Giá',
            artist: 'Tim',
            url: 'https://dl.dropboxusercontent.com/s/bpjqu0j6tshfdno/monquavogia.mp3',
            cover: 'https://i.imgur.com/wMvE7vm.jpg',
            theme: '#c51793',
        },
        {
            name: 'Em Thật Là Ngốc',
            artist: 'Vũ Duy Khánh',
            url: 'https://dl.dropboxusercontent.com/s/crszezp1aq3eass/emthatlangoc.mp3',
            cover: 'https://i.imgur.com/287Zj5e.jpg',
            theme: '#648392',
        },
        {
            name: 'Đâu Chỉ Có Mình Em',
            artist: 'Trịnh Tuấn Vỹ',
            url: 'https://dl.dropboxusercontent.com/s/g6h2pqsrnhl769n/dauchicominhem.mp3',
            cover: 'https://i.imgur.com/chQNecQ.jpg',
            theme: '#4ff9d9',
        },
        {
            name: 'Vì Sao',
            artist: 'Khởi My, Hoàng Rapper',
            url: 'https://dl.dropboxusercontent.com/s/17maeacydcjlztx/Vi-Sao-Khoi-My-Hoang-Rapper.mp3',
            cover: 'https://i.imgur.com/GNYy9KE.jpg',
            theme: '#c52517',
        },
        {
            name: 'Em Sẽ Là Người Ra Đi',
            artist: 'Cẩm Ly',
            url: 'https://dl.dropboxusercontent.com/s/h02b3o4lnh54rfu/emselanguoiradi.mp3',
            cover: 'https://i.imgur.com/7A888Hh.jpg',
            theme: '#a040fe',
        },
        {
            name: 'Tình Yêu Cao Thượng',
            artist: 'Phạm Quỳnh Anh',
            url: 'https://dl.dropboxusercontent.com/s/ba85ho4ovg09a6i/Tinh-Yeu-Cao-Thuong-Pham-Quynh-Anh.mp3',
            cover: 'https://i.imgur.com/lbStubi.jpg',
            theme: '#063b76',
        },
        {
            name: 'Lời Nguyền',
            artist: 'Akira Phan, Vũ Ngọc Diệp',
            url: 'https://dl.dropboxusercontent.com/s/od1cdlpk4tdm524/loinguyen.mp3',
            cover: 'https://i.imgur.com/fWGBx9E.jpg',
            theme: '#8bb47e',
        },
        {
            name: 'Yêu Vội Vàng',
            artist: 'Lê Bảo Bình',
            url: 'https://dl.dropboxusercontent.com/s/nc7alj61tyva9hg/yeuvoivang.mp3',
            cover: 'https://i.imgur.com/pQ1r8G2.jpg',
            theme: '#67ed38',
        },
        {
            name: 'Có Anh Ở Đây Rồi',
            artist: 'Anh Quân Idol',
            url: 'https://dl.dropboxusercontent.com/s/fstgd45upx766zl/coanhodayroi.mp3',
            cover: 'https://i.imgur.com/CUWVtiO.jpg',
            theme: '#4805e8',
        },
        {
            name: 'Thế Giới Của Anh',
            artist: 'Bùi Tuấn Ngọc',
            url: 'https://dl.dropboxusercontent.com/s/uoyvbxu2p0nw29f/thegioicuaanh.mp3',
            cover: 'https://i.imgur.com/xTV3Lss.jpg',
            theme: '#79f111',
        },
        {
            name: 'Tại Anh Không Dũng Cảm',
            artist: 'Akira Phan',
            url: 'https://dl.dropboxusercontent.com/s/cwhsu5qu272bcc7/taianhkhongdungcam.mp3',
            cover: 'https://i.imgur.com/fWGBx9E.jpg',
            theme: '#22b1ee',
        },
        {
            name: 'Làm Người Yêu Anh Nhé Baby',
            artist: '3 Chú Bộ Đội',
            url: 'https://dl.dropboxusercontent.com/s/v4f8x3trm07pd2w/lamnguoiyeuanhnhebaby.mp3',
            cover: 'https://i.imgur.com/ZYlSCg6.jpg',
            theme: '#538207',
        },
        {
            name: 'Yêu Thật Nhiều, Nhớ Thật Nhiều',
            artist: 'Asa, LDT',
            url: 'https://dl.dropboxusercontent.com/s/7watjj5zb95vsi0/yeuthatnhieunhothatnhieu.mp3',
            cover: 'https://i.imgur.com/QYNt6pv.jpg',
            theme: '#6856f7',
        },
        {
            name: 'Đừng Bắt Anh Chờ Đợi Nữa',
            artist: 'Dương Thiên Minh',
            url: 'https://dl.dropboxusercontent.com/s/8szzd12xlueei46/dungbatanhchodoinua.mp3',
            cover: 'https://i.imgur.com/W3klC9a.jpg',
            theme: '#0bda67',
        },
        {
            name: 'Chiều Hôm Ấy',
            artist: 'JayKii',
            url: 'https://dl.dropboxusercontent.com/s/0fxwkohbc0j7g5u/chieuhomay.mp3',
            cover: 'https://i.imgur.com/Isivd43.jpg',
            theme: '#a720b9',
        },
        {
            name: 'Chúc Em Hạnh Phúc',
            artist: 'Phan Duy Anh',
            url: 'https://dl.dropboxusercontent.com/s/wsvwz563eobxrvl/chucemhanhphuc.mp3',
            cover: 'https://i.imgur.com/JvWXlzJ.png',
            theme: '#38031b',
        },
        {
            name: 'Cơn Mưa Tuổi Thanh Xuân',
            artist: 'A.C Xuân Tài',
            url: 'https://dl.dropboxusercontent.com/s/jggza9rl4n0umc1/conmuatuoithanhxuan.mp3',
            cover: 'https://i.imgur.com/rd4IW2e.jpg',
            theme: '#563a2a',
        },
        {
            name: 'Khi Phải Quên Đi',
            artist: 'Phan Mạnh Quỳnh',
            url: 'https://dl.dropboxusercontent.com/s/prwvalr14655jht/Khi-Phai-Quen-Di-Phan-Manh-Quynh.mp3',
            cover: 'https://i.imgur.com/hHYvA65.jpg',
            theme: '#4b2f24',
        },
        {
            name: 'Tại Vì Anh',
            artist: 'Khắc Anh',
            url: 'https://dl.dropboxusercontent.com/s/3aqcxmylt2609le/taivianh.mp3',
            cover: 'https://i.imgur.com/0AZ4kbs.jpg',
            theme: '#f83146',
        },
        {
            name: 'Làm Sao Để Quên Em',
            artist: 'Du Thiên',
            url: 'https://dl.dropboxusercontent.com/s/izooc2hesjytvgp/lamsaodequenem.mp3',
            cover: 'https://i.imgur.com/Rmz8DtG.jpg',
            theme: '#ec75a5',
        },
        {
            name: 'Ngồi Nhà Tuyết Trắng',
            artist: 'Akira Phan',
            url: 'https://dl.dropboxusercontent.com/s/2sho71e6impgn3l/ngoinhatuyettrang.mp3',
            cover: 'https://i.imgur.com/fWGBx9E.jpg',
            theme: '#a3f48f',
        },
        {
            name: 'Bức Tranh Từ Nước Mắt',
            artist: 'Mr Siro',
            url: 'https://dl.dropboxusercontent.com/s/0si7bopafacqkg8/buctranhtunuocmat.mp3',
            cover: 'https://i.imgur.com/9Mf5CA5.jpg',
            theme: '#bf811e',
        },
        {
            name: 'Chỉ Anh Hiểu Em',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/0yb5amm8aehnpcn/Chi-Anh-Hieu-Em-Khac-Viet.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#f42935',
        },
        {
            name: 'Nỗi Đau Xót Xa',
            artist: 'Minh Vương M4U',
            url: 'https://dl.dropboxusercontent.com/s/qw2vy6tmvzuh8r5/NoiDauXotXaMinhVuongM4U.mp3',
            cover: 'https://i.imgur.com/PCzwbAw.jpg',
            theme: '#90fcdd',
        },
        {
            name: 'Vẫn Nhớ',
            artist: 'Tuấn Hưng',
            url: 'https://dl.dropboxusercontent.com/s/5fshgudk19rs8ps/vannho.mp3',
            cover: 'https://i.imgur.com/vTAAtNI.jpg',
            theme: '#7c9144',
        },
        {
            name: 'Sẽ Mãi Chờ',
            artist: 'Duy Khoa',
            url: 'https://dl.dropboxusercontent.com/s/ivx8wctypcforqm/semaicho.mp3',
            cover: 'https://i.imgur.com/RbAwzGk.jpg',
            theme: '#9ec55d',
        },
        {
            name: 'Tình Khuyết',
            artist: 'Hoàng Anh, Hoàng Hiếu',
            url: 'https://dl.dropboxusercontent.com/s/p9trdyvh7nfxqs6/tinhkhuyet.mp3',
            cover: 'https://i.imgur.com/xPLeM5V.jpg',
            theme: '#c9f987',
        },
        {
            name: 'Gương Mặt Lạ Lẫm',
            artist: 'Mr Siro',
            url: 'https://dl.dropboxusercontent.com/s/gdh8d7sdw6y9b7z/guongmatlalam.mp3',
            cover: 'https://i.imgur.com/9Mf5CA5.jpg',
            theme: '#b66e08',
        },
        {
            name: 'Tuyết Yêu Thương',
            artist: 'Young Uno',
            url: 'https://dl.dropboxusercontent.com/s/tl5y1c8jf6jred2/tuyetyeuthuong.mp3',
            cover: 'https://i.imgur.com/N8dOYLH.jpg',
            theme: '#a66691',
        },
        {
            name: 'Lại Một Lần Nữa',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/2jb5lpqhyitkajm/laimotlannua.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#ff426c',
        },
        {
            name: 'Vì Tôi Là Chàng Ngốc',
            artist: 'Minh Quân',
            url: 'https://dl.dropboxusercontent.com/s/m1vhrjjl242iuwn/vitoilachangngoc.mp3',
            cover: 'https://i.imgur.com/Gk62fIQ.jpg',
            theme: '#44020c',
        },
        {
            name: 'Lắng Nghe Nước Mắt',
            artist: 'Mr Siro',
            url: 'https://dl.dropboxusercontent.com/s/2ecpmea61dap490/langnghenuocmat.mp3',
            cover: 'https://i.imgur.com/9Mf5CA5.jpg',
            theme: '#1e7791',
        },
        {
            name: 'Tình Sắc Muôn Màu',
            artist: 'Lương Bích Hữu',
            url: 'https://dl.dropboxusercontent.com/s/k6m659c3n1zbius/tinhsacmuonmau.mp3',
            cover: 'https://i.imgur.com/wdjk5sF.jpg',
            theme: '#677c4f',
        },
        {
            name: 'Cần Quên Đi Hết',
            artist: 'Phạm Thế Anh',
            url: 'https://dl.dropboxusercontent.com/s/vfuvim9qynf74ms/canquendihet.mp3',
            cover: 'https://i.imgur.com/shft86s.jpg',
            theme: '#b25e44',
        },
        {
            name: 'Tội Cho Cô Gái Đó',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/beejrqfnlilfbd8/toichocogaido.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#d04977',
        },
        {
            name: 'Em Biết',
            artist: 'Trịnh Đình Quang',
            url: 'https://dl.dropboxusercontent.com/s/ut60nmxgrnpqvlf/embiettdq.mp3',
            cover: 'https://i.imgur.com/mJ5gwIk.jpg',
            theme: '#2dc9c8',
        },
        {
            name: 'Xin Đừng Hỏi Tại Sao',
            artist: 'Đinh Ứng Phi Trường',
            url: 'https://dl.dropboxusercontent.com/s/lqtpl933c1k6yvl/xindunghoitaisao.mp3',
            cover: 'https://i.imgur.com/XizUWgq.jpg',
            theme: '#5be1c8',
        },
        {
            name: 'Yêu Thương Vô Tình',
            artist: 'Gia Huy Singer',
            url: 'https://dl.dropboxusercontent.com/s/k48pqh5icqaaefh/YeuThuongVoTinhGiaHuy.mp3',
            cover: 'https://i.imgur.com/AU8XnLE.jpg',
            theme: '#e4bb6f',
        },
        {
            name: 'Em Là Ai Trong Anh',
            artist: 'Phan Ngọc Luân',
            url: 'https://dl.dropboxusercontent.com/s/cjv9umxuqy48pob/EmLaAiTrongAnhPhanNgocLuan.mp3',
            cover: 'https://i.imgur.com/p90Ebv0.jpg',
            theme: '#784b95',
        },
        {
            name: 'Hai Thế Giới',
            artist: 'Trương Đại Hải',
            url: 'https://dl.dropboxusercontent.com/s/x0eaa7x8xshta6z/Hai-The-Gioi-Truong-Dai-Hai.mp3',
            cover: 'https://i.imgur.com/FmoNoGb.jpg',
            theme: '#b5de99',
        },
        {
            name: 'Là Vì Anh',
            artist: 'Asa, Kim Joon Shin, LDT',
            url: 'https://dl.dropboxusercontent.com/s/r27agrat9xlpn0r/lavianh.mp3',
            cover: 'https://i.imgur.com/01U2wNo.jpg',
            theme: '#d59d2f',
        },
        {
            name: 'Chỉ Còn Trong Mơ',
            artist: 'Minh Vương M4U',
            url: 'https://dl.dropboxusercontent.com/s/gns7vehvsb6nxwl/ChiConTrongMoMinhVuongM4U.mp3',
            cover: 'https://i.imgur.com/PCzwbAw.jpg',
            theme: '#db4a3e',
        },
        {
            name: 'Yêu Lại Từ Đầu',
            artist: 'Khắc Việt',
            url: 'https://dl.dropboxusercontent.com/s/950xa482oz4xe7p/yeulaitudau.mp3',
            cover: 'https://i.imgur.com/oPCCCYh.jpg',
            theme: '#7dd280',
        },
        {
            name: 'Chia Tay Không Lý Do',
            artist: 'The Men',
            url: 'https://dl.dropboxusercontent.com/s/dd2b2tfsavxtxw2/chiataykhonglydo.mp3',
            cover: 'https://i.imgur.com/YjILcnQ.jpg',
            theme: '#77d4f8',
        },
        {
            name: 'Có Không Giữ Mất Đừng Tìm',
            artist: 'Cảnh Minh',
            url: 'https://dl.dropboxusercontent.com/s/x5st6gys0uh8mmc/Co-Khong-Giu-Mat-Dung-Tim-Canh-Minh.mp3',
            cover: 'https://i.imgur.com/BFE8xUJ.jpg',
            theme: '#b105f1',
        },
        {
            name: 'Anh Có Khỏe Không',
            artist: 'Hoàng Lan 2K',
            url: 'https://dl.dropboxusercontent.com/s/esb01h6e7jzwlft/anhcokhoekhong.mp3',
            cover: 'https://i.imgur.com/KJM4UGA.jpg',
            theme: '#9bb6d2',
        },
        {
            name: 'Em Ơi Em Đừng Khóc',
            artist: 'Cao Nam Thành',
            url: 'https://dl.dropboxusercontent.com/s/n2kmm61g9kpinkk/EmOiEmDungKhocCaoNamThanh.mp3',
            cover: 'https://i.imgur.com/0D5vFzb.jpg',
            theme: '#507917',
        },
        {
            name: 'Phai Dấu Cuộc Tình',
            artist: 'Quang Vinh',
            url: 'https://dl.dropboxusercontent.com/s/4ivmd2b6iwn783n/PhaiDauCuocTinhQuangVinhCover.mp3',
            cover: 'https://i.imgur.com/qI5LPTN.jpg',
            theme: '#01316f',
        },
        {
            name: 'Cho Em Một Lần Yêu',
            artist: 'Đông Nhi',
            url: 'https://dl.dropboxusercontent.com/s/698nahmku3qaopy/ChoEmMotLanYeuDongNhi.mp3',
            cover: 'https://i.imgur.com/we9AQmK.jpg',
            theme: '#2316e4',
        },
        {
            name: 'Giấc Mơ Có Thật',
            artist: 'Lệ Quyên',
            url: 'https://dl.dropboxusercontent.com/s/bkhrb6fm8wysr40/Giac-Mo-Co-That-Le-Quyen.mp3',
            cover: 'https://i.imgur.com/nS3xQq0.jpg',
            theme: '#8b895b',
        },
        {
            name: 'Bay Giữa Ngân Hà',
            artist: 'Nam Cường',
            url: 'https://dl.dropboxusercontent.com/s/wtoa46okvvq50rp/baygiuanganha.mp3',
            cover: 'https://i.imgur.com/8nmvUzm.png',
            theme: '#c1733a',
        },
        {
            name: 'Anh Nhớ Em Nhiều Lắm',
            artist: 'Cao Tùng Anh',
            url: 'https://dl.dropboxusercontent.com/s/rhmfj3fbh3dgopd/anhnhoemnhieulam.mp3',
            cover: 'https://i.imgur.com/3PRJtIE.jpg',
            theme: '#a00dc4',
        },
        {
            name: 'Chúc Em Hạnh Phúc',
            artist: 'Lee Quân',
            url: 'https://dl.dropboxusercontent.com/s/rqc5spubp3xgpfx/chucemhanhphuclq.mp3',
            cover: 'https://i.imgur.com/3qpL0iP.jpg',
            theme: '#d24253',
        },
        {
            name: 'Vì',
            artist: 'Vũ Duy Khánh',
            url: 'https://dl.dropboxusercontent.com/s/h01j0kzw45hapro/vi.mp3',
            cover: 'https://i.imgur.com/J0WZGH5.jpg',
            theme: '#4e32ff',
        },
        {
            name: 'Em Có Yêu Anh Không',
            artist: 'Khánh Phương',
            url: 'https://dl.dropboxusercontent.com/s/7e6w890feurj1zz/emcoyeuanhkhong.mp3',
            cover: 'https://i.imgur.com/K8ku397.jpg',
            theme: '#ca88e9',
        },
        {
            name: 'Ngày Xưa Em Đến',
            artist: 'Anh Khang',
            url: 'https://archive.org/download/musicnewxk/NgayXuaEmDen-AnhKhang.mp3',
            cover: 'https://i.imgur.com/tm1fjhf.jpeg',
            theme: '#1d95aa',
        },
        {
            name: 'Hãy Là Của Riêng Anh',
            artist: 'Nam Dương',
            url: 'https://dl.dropboxusercontent.com/s/ic2mauyh6lqavxp/HayLaCuaRiengAnhNamDuong.mp3',
            cover: 'https://i.imgur.com/CdYBFPU.jpg',
            theme: '#7b229a',
        },
        {
            name: 'Vợ Tuyệt Vời Nhất',
            artist: 'Vũ Duy Khánh',
            url: 'https://dl.dropboxusercontent.com/s/qpjok94rmn0nszd/votuyetvoinhat.mp3',
            cover: 'https://i.imgur.com/287Zj5e.jpg',
            theme: '#7a4a07',
        },
        {
            name: 'Vì Ai Đổi Thay',
            artist: 'Tuấn Hii',
            url: 'https://dl.dropboxusercontent.com/s/51xb0opp12ptvyb/ViAiDoiThayTuanHii.mp3',
            cover: 'https://i.imgur.com/tKWZOcD.jpg',
            theme: '#a14a40',
        },
        {
            name: 'Anh Cần Em',
            artist: 'Đường Tuấn Khang',
            url: 'https://dl.dropboxusercontent.com/s/y2gtgp8ehgtjv5h/anhcanem.mp3',
            cover: 'https://i.imgur.com/dSGXDjv.jpg',
            theme: '#64df6c',
        },
        {
            name: 'Hẹn Ngày Mai Yêu',
            artist: 'Long Cao',
            url: 'https://dl.dropboxusercontent.com/s/5a6rswndil43vii/HenNgayMaiYeuLongCao.mp3',
            cover: 'https://i.imgur.com/T7CDxyy.jpg',
            theme: '#fa946d',
        },
        {
            name: 'Yêu Không Nghỉ Phép',
            artist: 'Isaac, OnlyC',
            url: 'https://dl.dropboxusercontent.com/s/hebzi4plw5svvny/yeukhongnghiphep.mp3',
            cover: 'https://i.imgur.com/3b2SaMr.jpg',
            theme: '#f1f97a',
        },
        {
            name: 'Lời Thú Tội Ngọt Ngào',
            artist: 'Đông Nhi',
            url: 'https://dl.dropboxusercontent.com/s/0pqver5gu0tvr4x/LoiThuToiNgotNgaoDongNhi.mp3',
            cover: 'https://i.imgur.com/we9AQmK.jpg',
            theme: '#58c987',
        },
        {
            name: 'Bản Tình Ca Đầu Tiên',
            artist: 'Duy Khoa',
            url: 'https://dl.dropboxusercontent.com/s/hi96hb7g886utoy/BanTinhCaDauTienDuyKhoa.mp3',
            cover: 'https://i.imgur.com/RbAwzGk.jpg',
            theme: '#5094bf',
        },
        {
            name: 'Thêm Một Lần Đau',
            artist: 'HKT',
            url: 'https://dl.dropboxusercontent.com/s/xrs092qaixt36av/themmotlandau.mp3',
            cover: 'https://i.imgur.com/RnHIt53.jpg',
            theme: '#ff2714',
        },
        {
            name: 'Vợ Yêu',
            artist: 'Vũ Duy Khánh, Khắc Anh',
            url: 'https://dl.dropboxusercontent.com/s/ytqst4m5y540zc3/VoYeuVuDuyKhanhKhacAnh.mp3',
            cover: 'https://i.imgur.com/287Zj5e.jpg',
            theme: '#c7b5d5',
        },
        {
            name: 'Mashup Lỡ Duyên',
            artist: 'Gia Huy Singer, Kenbi Trần',
            url: 'https://dl.dropboxusercontent.com/s/zoplhxlp4x9g2zq/MashupLoDuyenGiaHuyKenbiTran.mp3',
            cover: 'https://i.imgur.com/AU8XnLE.jpg',
            theme: '#7ce05f',
        },
        {
            name: 'Đôi Mắt',
            artist: 'Wanbi Tuấn Anh',
            url: 'https://dl.dropboxusercontent.com/s/06pzx10x5cdp9pp/DoiMatWanbiTuanAnh.mp3',
            cover: 'https://i.imgur.com/1sAExur.jpg',
            theme: '#609db4',
        },
        {
            name: 'Người Yêu Tương Lai',
            artist: 'Thảo Phạm',
            url: 'https://dl.dropboxusercontent.com/s/xv1uymdeonkpbey/NguoiYeuTuongLaiThaoPham.mp3',
            cover: 'https://i.imgur.com/w2zqfWj.jpg',
            theme: '#cc3acb',
        },
        {
            name: 'Hãy Về Đây Bên Anh',
            artist: 'Duy Mạnh',
            url: 'https://dl.dropboxusercontent.com/s/7v1c8i8gdkw5oes/HayVeDayBenAnhDuyManh.mp3',
            cover: 'https://i.imgur.com/yLrGkIS.jpg',
            theme: '#032967',
        },
        {
            name: 'Người Đã Từng Thương',
            artist: 'Thái Lan Viên',
            url: 'https://dl.dropboxusercontent.com/s/myec4m2xahbh3im/Nguoi-Da-Tung-Thuong-Thai-Lan-Vien.mp3',
            cover: 'https://i.imgur.com/JANR14z.jpg',
            theme: '#9fdad0',
        },
        {
            name: 'Nước Mắt Hạnh Phúc',
            artist: 'Nguyên Khôi',
            url: 'https://dl.dropboxusercontent.com/s/t2j275zppxlf6h7/Nuoc-Mat-Hanh-Phuc-Nguyen-Khoi.mp3',
            cover: 'https://i.imgur.com/puhRbt2.jpg',
            theme: '#9260de',
        },
        {
            name: 'Hết',
            artist: 'Trương Đại Hải',
            url: 'https://dl.dropboxusercontent.com/s/dkmqbxgzipkdq51/Het-Truong-Dai-Hai.mp3',
            cover: 'https://i.imgur.com/FmoNoGb.jpg',
            theme: '#9ffab8',
        },
        {
            name: 'Giây Phút Chia Xa 1',
            artist: 'Duy Mạnh',
            url: 'https://dl.dropboxusercontent.com/s/1au5cq59w8xmlbr/Giay-Phut-Chia-Xa-1-Duy-Manh.mp3',
            cover: 'https://i.imgur.com/yLrGkIS.jpg',
            theme: '#a38f55',
        },
        {
            name: 'Khóc',
            artist: 'Đông Nhi',
            url: 'https://dl.dropboxusercontent.com/s/witfrarmbhz6a8p/KhocDongNhi.mp3',
            cover: 'https://i.imgur.com/we9AQmK.jpg',
            theme: '#fc4e8e',
        },
        {
            name: 'Anh Chỉ Biết Câm Nín NTEK',
            artist: 'Ưng Hoàng Phúc',
            url: 'https://dl.dropboxusercontent.com/s/jf95joiyswe6su0/Anh-Chi-Biet-Cam-Nin-Nghe-Tieng-Em-Khoc-Ung-Hoang-Phuc.mp3',
            cover: 'https://i.imgur.com/Y7xkAA6.jpg',
            theme: '#4df4d0',
        },
        {
            name: 'Chúc Vợ Ngủ Ngon',
            artist: 'Vũ Duy Khánh',
            url: 'https://dl.dropboxusercontent.com/s/ay5m0kgre61dgap/ChucVoNguNgonVuDuyKhanh.mp3',
            cover: 'https://i.imgur.com/287Zj5e.jpg',
            theme: '#5a6fc7',
        },
        {
            name: 'Dằm Trong Tim',
            artist: 'Lương Bích Hữu',
            url: 'https://dl.dropboxusercontent.com/s/nz5ct6dah3lgc2u/Dam-Trong-Tim-Luong-Bich-Huu.mp3',
            cover: 'https://i.imgur.com/wdjk5sF.jpg',
            theme: '#3ebe4f',
        },
        {
            name: 'Dòng Sông Buồn',
            artist: 'Bằng Cường',
            url: 'https://dl.dropboxusercontent.com/s/hz4c66exnverqc1/Dong-Song-Buon-Bang-Cuong.mp3',
            cover: 'https://i.imgur.com/JFJ9Vw3.jpg',
            theme: '#0746ab',
        },
        {
            name: 'Không Thở Được',
            artist: 'Phạm Quỳnh Anh',
            url: 'https://dl.dropboxusercontent.com/s/lb8k5rhb6az7gd4/Khong-Tho-Duoc-Pham-Quynh-Anh.mp3',
            cover: 'https://i.imgur.com/lbStubi.jpg',
            theme: '#7f4a85',
        },
        {
            name: 'Ngồi Bên Em',
            artist: 'Phan Đình Tùng',
            url: 'https://dl.dropboxusercontent.com/s/oe0uyp35fwf4p9n/Ngoi-Ben-Em-Phan-Dinh-Tung.mp3',
            cover: 'https://i.imgur.com/tSh4l5L.jpg',
            theme: '#308d4b',
        },
        {
            name: 'Càng Yêu Càng Đau',
            artist: 'Katy Trang',
            url: 'https://dl.dropboxusercontent.com/s/jdq8uf38ar3lf5r/Cang-Yeu-Cang-Dau-Katy-Trang.mp3',
            cover: 'https://i.imgur.com/9EOAXC4.jpg',
            theme: '#050f9a',
        },
        {
            name: 'Người Thứ Ba',
            artist: 'Thanh Thảo',
            url: 'https://dl.dropboxusercontent.com/s/zr4ir3k1hh8mc44/Nguoi-Thu-Ba-Thanh-Thao.mp3',
            cover: 'https://i.imgur.com/xdgfUTF.jpg',
            theme: '#8a6e28',
        },
        {
            name: 'Tìm Lại Bầu Trời',
            artist: 'Tuấn Hưng',
            url: 'https://dl.dropboxusercontent.com/s/sbuuouawed1ge96/TimLaiBauTroiTuanHung.mp3',
            cover: 'https://i.imgur.com/vTAAtNI.jpg',
            theme: '#1333dc',
        },
        {
            name: 'Tình Thôi Xót Xa',
            artist: 'Lam Trường',
            url: 'https://dl.dropboxusercontent.com/s/su7p3g78an1t307/Tinh-Thoi-Xot-Xa-Lam-Truong.mp3',
            cover: 'https://i.imgur.com/OdoPN6V.jpg',
            theme: '#cc4d54',
        },
        {
            name: 'Vẫn Nhớ Người',
            artist: 'Ngô Trường',
            url: 'https://dl.dropboxusercontent.com/s/o09v3a3nngd7krb/Van-Nho-Nguoi-Ngo-Truong.mp3',
            cover: 'https://i.imgur.com/cCKRnvX.jpg',
            theme: '#45c37c',
        },
        {
            name: 'Hãy Tha Thứ Cho Anh',
            artist: 'Cao Thái Sơn',
            url: 'https://dl.dropboxusercontent.com/s/adtkv7hazlqpug0/Hay-Tha-Thu-Cho-Anh-Cao-Thai-Son.mp3',
            cover: 'https://i.imgur.com/e1348TX.jpg',
            theme: '#55f12d',
        },
        {
            name: 'Tình Yêu Hoa Gió',
            artist: 'Trương Thế Vinh',
            url: 'https://dl.dropboxusercontent.com/s/l73pm1ektk3fbad/TinhYeuHoaGioTruongTheVinh.mp3',
            cover: 'https://i.imgur.com/Mjw8j7j.jpg',
            theme: '#0d9866',
        },
        {
            name: 'Hãy Để Anh Yêu Em Lần Nữa',
            artist: 'The Men',
            url: 'https://dl.dropboxusercontent.com/s/tnup5c2ceu4lu2i/Hay-De-Anh-Yeu-Em-Lan-Nua-The-Men.mp3',
            cover: 'https://i.imgur.com/YjILcnQ.jpg',
            theme: '#f12843',
        },
        {
            name: 'Người Thứ Ba',
            artist: 'Ưng Hoàng Phúc',
            url: 'https://dl.dropboxusercontent.com/s/6mrct24k337f6ou/Nguoi-Thu-Ba-Ung-Hoang-Phuc.mp3',
            cover: 'https://i.imgur.com/Y7xkAA6.jpg',
            theme: '#5b47ff',
        },
        {
            name: 'Mong Em Luôn Hạnh Phúc',
            artist: 'Phan Đình Tùng',
            url: 'https://dl.dropboxusercontent.com/s/uvknbnwncysy6xr/Mong-Em-Luon-Hanh-Phuc-Phan-Dinh-Tung.mp3',
            cover: 'https://i.imgur.com/tSh4l5L.jpg',
            theme: '#0cfba9',
        },
        {
            name: 'Anh',
            artist: 'Hồ Quỳnh Hương',
            url: 'https://dl.dropboxusercontent.com/s/uegi2r18jccbk72/Anh-Ho-Quynh-Huong.mp3',
            cover: 'https://i.imgur.com/nGZm1xH.jpg',
            theme: '#e608ee',
        },
        {
            name: 'Tình Xưa Nghĩa Cũ',
            artist: 'Jimmii Nguyễn',
            url: 'https://dl.dropboxusercontent.com/s/ec29ikhhypvdjd5/TinhXuaNghiaCuJimmiiNguyen.mp3',
            cover: 'https://i.imgur.com/WGtkWNL.jpg',
            theme: '#9ac868',
        },
        {
            name: 'Em Nhớ Anh Rất Nhiều',
            artist: 'Sơn Ca',
            url: 'https://dl.dropboxusercontent.com/s/hnt8g3b8tivv34z/Em-Nho-Anh-Rat-Nhieu-Son-Ca.mp3',
            cover: 'https://i.imgur.com/pAtoRGS.jpg',
            theme: '#769512',
        },
        {
            name: 'Nụ Hôn Và Nước Mắt',
            artist: 'Lâm Chấn Huy',
            url: 'https://dl.dropboxusercontent.com/s/hyics5h2qvpntb9/Nu-Hon-Va-Nuoc-Mat-Lam-Chan-Huy.mp3',
            cover: 'https://imgur.com/LXe6DG1',
            theme: '#76bd3c',
        },
        {
            name: 'Thầm Mong Anh Quay Về Bên Em',
            artist: 'Mây Trắng',
            url: 'https://dl.dropboxusercontent.com/s/7lievw4vvqloj4m/Tham-Mong-Anh-Quay-Ve-Ben-Em-May-Trang.mp3',
            cover: 'https://i.imgur.com/bnXgf4l.jpg',
            theme: '#a6096b',
        },
    ]
});